const en = {
  title: "Plan and usage",
  current: "Current plan",
  usage: "Usage",
  change: "Change plan",
  upgrade: "Upgrade plan",
  remaining: "{n} remaining",
  unlimited: "Unlimited",
  unknown: "Not specified",
  noPlan: "No active plan",
  month: "month",
  year: "year",
  custom: "Contact us",
  close: "Cancel",
  choose: "Choose {plan}",
  selected: "Current plan",
  warning: "You are approaching your {plan} limit.",
  reached: "The limit for {resource} has been reached.",
  loadError: "We couldn't load plan usage.",
  retry: "Try again",
  checkout: "Continue to billing",
  unavailable:
    "Billing integration is not available yet. Your subscription has not changed.",
  preview: "Plan preview only. No subscription or payment is changed.",
  loading: "Loading usage…",
  accountSettings: "Account settings",
  resources: {
    activeCustomers: "Active customers",
    locations: "Business locations",
  },
};
export const usageContent = {
  en,
  ru: {
    title: "Тариф и использование",
    current: "Текущий тариф",
    usage: "Использование",
    change: "Изменить тариф",
    upgrade: "Увеличить тариф",
    remaining: "Осталось {n}",
    unlimited: "Без ограничений",
    unknown: "Не определено",
    noPlan: "Нет активного тарифа",
    month: "месяц",
    year: "год",
    custom: "Связаться",
    close: "Отмена",
    choose: "Выбрать {plan}",
    selected: "Текущий тариф",
    warning: "Вы приближаетесь к лимиту тарифа {plan}.",
    reached: "Лимит ресурса «{resource}» достигнут.",
    loadError: "Не удалось загрузить использование тарифа.",
    retry: "Повторить",
    checkout: "Продолжить оплату",
    unavailable:
      "Платёжная интеграция пока недоступна. Ваша подписка не изменена.",
    preview: "Предпросмотр тарифа. Подписка и оплата не изменяются.",
    loading: "Загрузка использования…",
    accountSettings: "Настройки аккаунта",
    resources: {
      activeCustomers: "Активные клиенты",
      locations: "Точки бизнеса",
    },
  },
  lv: {
    title: "Plāns un lietojums",
    current: "Pašreizējais plāns",
    usage: "Lietojums",
    change: "Mainīt plānu",
    upgrade: "Paaugstināt plānu",
    remaining: "Atlikuši {n}",
    unlimited: "Neierobežots",
    unknown: "Nav noteikts",
    noPlan: "Nav aktīva plāna",
    month: "mēnesī",
    year: "gadā",
    custom: "Sazināties",
    close: "Atcelt",
    choose: "Izvēlēties {plan}",
    selected: "Pašreizējais plāns",
    warning: "Tuvojaties plāna {plan} limitam.",
    reached: "Resursa «{resource}» limits ir sasniegts.",
    loadError: "Neizdevās ielādēt plāna lietojumu.",
    retry: "Mēģināt vēlreiz",
    checkout: "Turpināt norēķinus",
    unavailable:
      "Norēķinu integrācija vēl nav pieejama. Abonements nav mainīts.",
    preview: "Plāna priekšskatījums. Abonements un maksājums netiek mainīts.",
    loading: "Ielādē lietojumu…",
    accountSettings: "Konta iestatījumi",
    resources: {
      activeCustomers: "Aktīvie klienti",
      locations: "Uzņēmuma atrašanās vietas",
    },
  },
};
