import type { Locale } from "@/content";
const en = {
  create: {
    customers: "Add customer",
    loyalty: "Create loyalty program",
    memberships: "Create membership",
    offers: "Create offer",
    automations: "Prepare return journey",
  },
  intro: {
    customers: "Your customers, their profiles and your relationship history.",
    loyalty:
      "Configure the experience that gives customers a reason to return.",
    memberships:
      "Memberships and prepaid packages, in one customer relationship.",
    offers: "Prepare personal offers for the right moment.",
    automations:
      "Prepare return journeys. Execution starts after backend activation.",
  },
  empty: {
    customers: "Add your first customer or prepare customer connection.",
    loyalty: "Create a stamps or points program and define the reward.",
    memberships: "Prepare a membership or a prepaid visit package.",
    offers: "Create an offer and choose its intended audience.",
    automations:
      "Choose an inactivity trigger, an offer and a delivery channel.",
  },
  fields: {
    name: "Name",
    email: "Email",
    phone: "Phone",
    notes: "Notes",
    kind: "Type",
    target: "Reward threshold",
    reward: "Reward",
    description: "Description",
    price: "Price",
    currency: "Currency",
    visits: "Included visits (optional)",
    interval: "Billing interval",
    audience: "Audience",
    expiresAt: "Expiry date (optional)",
    inactivityDays: "Days without a visit",
    offerId: "Return offer",
    channel: "Delivery channel",
  },
  options: {
    stamps: "Stamps",
    points: "Points",
    membership: "Membership",
    package: "Prepaid package",
    monthly: "Monthly",
    yearly: "Yearly",
    all: "All connected customers",
    returning: "Returning customers",
    inactive: "Inactive customers",
    memberflow: "MemberFlow notifications",
    wallet: "Wallet",
  },
  all: "Current",
  archived: "Archived",
  search: "Search by name",
  save: "Save draft",
  saveCustomer: "Save customer",
  saving: "Saving…",
  saved: "Saved in this browser tab.",
  edit: "Edit",
  details: "View details",
  archive: "Archive",
  restore: "Restore",
  cancel: "Cancel",
  close: "Close",
  draft: "Draft",
  contact: "Contact details",
  profile: "Customer profile",
  noContact: "No contact details supplied.",
  noResults: "No matching records.",
  error: "We couldn’t load this section.",
  retry: "Try again",
  saveError: "We couldn’t save your changes. Please try again.",
  preview: "Preview",
  demoNotice:
    "Changes in this preview stay in this browser tab. No messages, payments or rewards are processed.",
  apiNotice: "Saving will become available after the service is connected.",
  required: "Enter a name.",
  selectOffer: "Choose an offer",
  noOffer: "Create a return offer first.",
  offerLink: "Open offers",
  inactivity: "Days without a visit",
  notRunning: "Not running",
  activate: "Activation requires the connected service.",
  noHistory: "Visit history appears after customers start visiting.",
  noAssignments: "Customer assignments and usage will appear after activation.",
  rewardLabel: "Next reward",
  thresholdLabel: "Reward threshold",
  usage: "Included visits",
  audienceLabel: "Intended audience",
  expiry: "Expires",
  noExpiry: "No expiry date",
  flow: ["Trigger", "Offer", "Delivery"],
  configure: "Configure",
  connection: "Customer connection",
  connectionIntro: "Connect a visit to a customer profile and a digital card.",
  setupQr: "Business QR & A4 sign",
  noQr: "Business QR and signed Wallet cards are not available in this preview.",
  settingsTabs: {
    business: "Business",
    profile: "Your profile",
    billing: "Plan & billing",
  },
  businessName: "Business name",
  category: "Business type",
  city: "City",
  country: "Country",
  description: "Short description",
  website: "Website",
  instagram: "Instagram",
  accent: "Brand color",
  logo: "Business logo",
  firstName: "First name",
  saveSettings: "Save changes",
  billingTitle: "Your plan",
  billingUnavailable:
    "Billing management becomes available after subscription activation.",
  status: "Subscription status",
  notActivated: "Not activated in preview",
  nextBilling: "Next billing date",
  notAvailable: "Not available",
  connectionUnavailable:
    "This channel is not connected. Authorization will open here when the integration is available.",
  connected: "Connection status comes from the business service.",
  noCredentials: "No credentials are requested here.",
  channelDetails: "Channel details",
  socialPurpose: "Campaign discovery and distribution",
  walletPurpose: "Customer cards and ongoing connection",
  removeLogo: "Remove logo",
  imageError: "Choose a JPEG, PNG or WebP image under 2 MB.",
  logoHint: "JPEG, PNG or WebP, up to 2 MB.",
  goals: "Business goals",
  role: "Business role",
  choose: "Select",
  stats: ["Visits", "Loyalty", "Membership"],
  notRecorded: "No history yet",
  viewActivity: "Customer activity",
  activationNote: "This is a configuration draft. It is not an active program.",
  noOffers: "No offers selected",
  noValue: "Not supplied",
};
type Copy = {
  [K in keyof typeof en]: (typeof en)[K] extends string
    ? string
    : (typeof en)[K] extends string[]
      ? string[]
      : { [P in keyof (typeof en)[K]]: string };
};
const ru: Copy = {
  create: {
    customers: "Добавить клиента",
    loyalty: "Создать программу лояльности",
    memberships: "Создать абонемент",
    offers: "Создать предложение",
    automations: "Подготовить сценарий возврата",
  },
  intro: {
    customers: "Клиенты, их профили и история ваших отношений.",
    loyalty: "Настройте клиентский опыт, который даёт повод вернуться.",
    memberships:
      "Абонементы и пакеты посещений в контексте отношений с клиентом.",
    offers: "Подготовьте личные предложения для подходящего момента.",
    automations:
      "Подготовьте сценарии возврата. Запуск станет доступен после подключения сервиса.",
  },
  empty: {
    customers: "Добавьте первого клиента или подготовьте подключение клиентов.",
    loyalty: "Создайте программу с отметками или баллами и определите награду.",
    memberships: "Подготовьте абонемент или пакет оплаченных посещений.",
    offers: "Создайте предложение и выберите его аудиторию.",
    automations: "Выберите условие неактивности, предложение и канал доставки.",
  },
  fields: {
    name: "Название",
    email: "Email",
    phone: "Телефон",
    notes: "Заметки",
    kind: "Тип",
    target: "Порог получения награды",
    reward: "Награда",
    description: "Описание",
    price: "Цена",
    currency: "Валюта",
    visits: "Включённые посещения (необязательно)",
    interval: "Период оплаты",
    audience: "Аудитория",
    expiresAt: "Срок действия (необязательно)",
    inactivityDays: "Дней без посещения",
    offerId: "Предложение для возврата",
    channel: "Канал доставки",
  },
  options: {
    stamps: "Отметки",
    points: "Баллы",
    membership: "Абонемент",
    package: "Пакет посещений",
    monthly: "Ежемесячно",
    yearly: "Ежегодно",
    all: "Все подключённые клиенты",
    returning: "Возвращающиеся клиенты",
    inactive: "Неактивные клиенты",
    memberflow: "Уведомления MemberFlow",
    wallet: "Wallet",
  },
  all: "Текущие",
  archived: "Архив",
  search: "Поиск по имени",
  save: "Сохранить черновик",
  saveCustomer: "Сохранить клиента",
  saving: "Сохраняем…",
  saved: "Сохранено в текущей вкладке браузера.",
  edit: "Редактировать",
  details: "Подробнее",
  archive: "В архив",
  restore: "Восстановить",
  cancel: "Отмена",
  close: "Закрыть",
  draft: "Черновик",
  contact: "Контактные данные",
  profile: "Профиль клиента",
  noContact: "Контактные данные не указаны.",
  noResults: "Подходящих записей нет.",
  error: "Не удалось загрузить раздел.",
  retry: "Попробовать снова",
  saveError: "Не удалось сохранить изменения. Попробуйте снова.",
  preview: "Предпросмотр",
  demoNotice:
    "Изменения сохраняются в текущей вкладке. Сообщения, оплата и награды не обрабатываются.",
  apiNotice: "Сохранение станет доступно после подключения сервиса.",
  required: "Введите название.",
  selectOffer: "Выберите предложение",
  noOffer: "Сначала создайте предложение для возврата.",
  offerLink: "Открыть предложения",
  inactivity: "Дней без посещения",
  notRunning: "Не запущено",
  activate: "Для запуска нужен подключённый сервис.",
  noHistory: "История появится после первых посещений клиентов.",
  noAssignments:
    "Назначения клиентам и использование появятся после активации.",
  rewardLabel: "Следующая награда",
  thresholdLabel: "Порог награды",
  usage: "Включённые посещения",
  audienceLabel: "Аудитория предложения",
  expiry: "Действует до",
  noExpiry: "Без срока действия",
  flow: ["Условие", "Предложение", "Доставка"],
  configure: "Настроить",
  connection: "Подключение клиентов",
  connectionIntro: "Свяжите визит с клиентским профилем и цифровой картой.",
  setupQr: "QR бизнеса и лист A4",
  noQr: "QR бизнеса и подписанные Wallet-карты недоступны в этом предпросмотре.",
  settingsTabs: {
    business: "Бизнес",
    profile: "Ваш профиль",
    billing: "Тариф и оплата",
  },
  businessName: "Название бизнеса",
  category: "Тип бизнеса",
  city: "Город",
  country: "Страна",
  description: "Краткое описание",
  website: "Сайт",
  instagram: "Instagram",
  accent: "Цвет бренда",
  logo: "Логотип бизнеса",
  firstName: "Имя",
  saveSettings: "Сохранить изменения",
  billingTitle: "Ваш тариф",
  billingUnavailable:
    "Управление оплатой станет доступно после активации подписки.",
  status: "Статус подписки",
  notActivated: "Не активирована в предпросмотре",
  nextBilling: "Следующая оплата",
  notAvailable: "Недоступно",
  connectionUnavailable:
    "Канал не подключён. Авторизация появится здесь, когда интеграция станет доступна.",
  connected: "Статус подключения получен от сервиса бизнеса.",
  noCredentials: "Здесь не запрашиваются учётные данные.",
  channelDetails: "Информация о канале",
  socialPurpose: "Привлечение и распространение кампаний",
  walletPurpose: "Карты клиентов и постоянная связь",
  removeLogo: "Убрать логотип",
  imageError: "Выберите JPEG, PNG или WebP размером до 2 МБ.",
  logoHint: "JPEG, PNG или WebP, до 2 МБ.",
  goals: "Цели бизнеса",
  role: "Роль в бизнесе",
  choose: "Выбрать",
  stats: ["Посещения", "Лояльность", "Абонемент"],
  notRecorded: "Истории пока нет",
  viewActivity: "Активность клиентов",
  activationNote: "Это черновик настройки. Программа ещё не активна.",
  noOffers: "Предложение не выбрано",
  noValue: "Не указано",
};
const lv: Copy = {
  create: {
    customers: "Pievienot klientu",
    loyalty: "Izveidot lojalitātes programmu",
    memberships: "Izveidot abonementu",
    offers: "Izveidot piedāvājumu",
    automations: "Sagatavot atgriešanās ceļu",
  },
  intro: {
    customers: "Klienti, viņu profili un jūsu attiecību vēsture.",
    loyalty: "Iestatiet klientu pieredzi, kas dod iemeslu atgriezties.",
    memberships:
      "Abonementi un apmeklējumu paketes klientu attiecību kontekstā.",
    offers: "Sagatavojiet personīgus piedāvājumus īstajam brīdim.",
    automations:
      "Sagatavojiet atgriešanās ceļus. Izpilde būs pieejama pēc pakalpojuma pievienošanas.",
  },
  empty: {
    customers:
      "Pievienojiet pirmo klientu vai sagatavojiet klientu savienojumu.",
    loyalty: "Izveidojiet zīmogu vai punktu programmu un nosakiet atlīdzību.",
    memberships: "Sagatavojiet abonementu vai apmaksātu apmeklējumu paketi.",
    offers: "Izveidojiet piedāvājumu un izvēlieties auditoriju.",
    automations:
      "Izvēlieties neaktivitātes nosacījumu, piedāvājumu un piegādes kanālu.",
  },
  fields: {
    name: "Nosaukums",
    email: "E-pasts",
    phone: "Tālrunis",
    notes: "Piezīmes",
    kind: "Veids",
    target: "Atlīdzības slieksnis",
    reward: "Atlīdzība",
    description: "Apraksts",
    price: "Cena",
    currency: "Valūta",
    visits: "Iekļautie apmeklējumi (neobligāti)",
    interval: "Norēķinu periods",
    audience: "Auditorija",
    expiresAt: "Derīguma termiņš (neobligāti)",
    inactivityDays: "Dienas bez apmeklējuma",
    offerId: "Atgriešanās piedāvājums",
    channel: "Piegādes kanāls",
  },
  options: {
    stamps: "Zīmogi",
    points: "Punkti",
    membership: "Abonements",
    package: "Apmeklējumu pakete",
    monthly: "Katru mēnesi",
    yearly: "Katru gadu",
    all: "Visi pievienotie klienti",
    returning: "Atkārtotie klienti",
    inactive: "Neaktīvie klienti",
    memberflow: "MemberFlow paziņojumi",
    wallet: "Wallet",
  },
  all: "Pašreizējie",
  archived: "Arhivētie",
  search: "Meklēt pēc nosaukuma",
  save: "Saglabāt melnrakstu",
  saveCustomer: "Saglabāt klientu",
  saving: "Saglabā…",
  saved: "Saglabāts šajā pārlūka cilnē.",
  edit: "Rediģēt",
  details: "Skatīt detaļas",
  archive: "Arhivēt",
  restore: "Atjaunot",
  cancel: "Atcelt",
  close: "Aizvērt",
  draft: "Melnraksts",
  contact: "Kontaktinformācija",
  profile: "Klienta profils",
  noContact: "Kontaktinformācija nav norādīta.",
  noResults: "Nav atbilstošu ierakstu.",
  error: "Neizdevās ielādēt sadaļu.",
  retry: "Mēģināt vēlreiz",
  saveError: "Neizdevās saglabāt izmaiņas. Mēģiniet vēlreiz.",
  preview: "Priekšskatījums",
  demoNotice:
    "Izmaiņas saglabājas šajā cilnē. Ziņas, maksājumi un atlīdzības netiek apstrādātas.",
  apiNotice: "Saglabāšana būs pieejama pēc pakalpojuma pievienošanas.",
  required: "Ievadiet nosaukumu.",
  selectOffer: "Izvēlieties piedāvājumu",
  noOffer: "Vispirms izveidojiet atgriešanās piedāvājumu.",
  offerLink: "Atvērt piedāvājumus",
  inactivity: "Dienas bez apmeklējuma",
  notRunning: "Nav palaists",
  activate: "Palaišanai vajadzīgs pievienots pakalpojums.",
  noHistory: "Vēsture parādīsies pēc pirmajiem klientu apmeklējumiem.",
  noAssignments: "Klientu piesaiste un lietošana parādīsies pēc aktivizācijas.",
  rewardLabel: "Nākamā atlīdzība",
  thresholdLabel: "Atlīdzības slieksnis",
  usage: "Iekļautie apmeklējumi",
  audienceLabel: "Piedāvājuma auditorija",
  expiry: "Derīgs līdz",
  noExpiry: "Bez termiņa",
  flow: ["Nosacījums", "Piedāvājums", "Piegāde"],
  configure: "Iestatīt",
  connection: "Klientu savienojums",
  connectionIntro:
    "Savienojiet apmeklējumu ar klienta profilu un digitālo karti.",
  setupQr: "Uzņēmuma QR un A4 plakāts",
  noQr: "Uzņēmuma QR un parakstītas Wallet kartes nav pieejamas šajā priekšskatījumā.",
  settingsTabs: {
    business: "Uzņēmums",
    profile: "Jūsu profils",
    billing: "Plāns un norēķini",
  },
  businessName: "Uzņēmuma nosaukums",
  category: "Uzņēmuma veids",
  city: "Pilsēta",
  country: "Valsts",
  description: "Īss apraksts",
  website: "Vietne",
  instagram: "Instagram",
  accent: "Zīmola krāsa",
  logo: "Uzņēmuma logo",
  firstName: "Vārds",
  saveSettings: "Saglabāt izmaiņas",
  billingTitle: "Jūsu plāns",
  billingUnavailable:
    "Norēķinu pārvaldība būs pieejama pēc abonementa aktivizācijas.",
  status: "Abonementa stāvoklis",
  notActivated: "Priekšskatījumā nav aktivizēts",
  nextBilling: "Nākamais maksājums",
  notAvailable: "Nav pieejams",
  connectionUnavailable:
    "Kanāls nav pievienots. Autorizācija parādīsies, kad integrācija būs pieejama.",
  connected: "Savienojuma stāvoklis saņemts no uzņēmuma pakalpojuma.",
  noCredentials: "Šeit netiek pieprasīti piekļuves dati.",
  channelDetails: "Kanāla detaļas",
  socialPurpose: "Klientu piesaiste un kampaņu izplatīšana",
  walletPurpose: "Klientu kartes un pastāvīgs savienojums",
  removeLogo: "Noņemt logo",
  imageError: "Izvēlieties JPEG, PNG vai WebP attēlu līdz 2 MB.",
  logoHint: "JPEG, PNG vai WebP, līdz 2 MB.",
  goals: "Uzņēmuma mērķi",
  role: "Loma uzņēmumā",
  choose: "Izvēlēties",
  stats: ["Apmeklējumi", "Lojalitāte", "Abonements"],
  notRecorded: "Vēl nav vēstures",
  viewActivity: "Klientu aktivitāte",
  activationNote: "Šis ir iestatījumu melnraksts, nevis aktīva programma.",
  noOffers: "Nav izvēlēta piedāvājuma",
  noValue: "Nav norādīts",
};
export const moduleContent: Record<Locale, Copy> = { en, lv, ru };
export type ModuleContent = Copy;
