import type { Locale } from "@/content";
const en = {
  activeFilter: "Active",
  completedFilter: "Completed",
  openCampaign: "Open campaign",
  created: "Created",
  campaignIntro: "Create the idea once. Prepare it for every channel.",
  newCampaign: "Create campaign",
  all: "All campaigns",
  drafts: "Drafts",
  search: "Find a campaign",
  noResults: "No matching campaigns.",
  emptyTitle: "Your next campaign starts with one idea.",
  emptyText:
    "An offer, product, service or event. Give it a name, add the details and choose where it should go.",
  source: "Create",
  adapt: "Prepare",
  distribute: "Distribute",
  sourceText: "Your business idea",
  adaptText: "Channel-specific content",
  distributeText: "Publishing through connected channels",
  editorTitle: "Create your campaign",
  editTitle: "Campaign details",
  title: "Campaign name",
  kind: "What are you promoting?",
  kinds: {
    offer: "Offer",
    product: "Product",
    service: "Service",
    event: "Event",
    announcement: "Announcement",
  },
  description: "Details",
  descriptionHint: "What should your customers know?",
  price: "Price (optional)",
  currency: "Currency",
  channels: "Destination channels",
  channelsHint:
    "Select destinations to prepare. This does not connect accounts or publish content.",
  save: "Save draft",
  saving: "Saving…",
  cancel: "Cancel",
  saved: "Draft saved.",
  draftNotice:
    "In this preview, drafts are saved in this browser tab only. Nothing is published.",
  apiNotice: "Campaign saving will be available when the backend is connected.",
  saveError: "We couldn’t save your draft. Please try again.",
  required: "Enter a campaign name.",
  image: "Campaign photo (optional)",
  imageHint: "JPEG, PNG or WebP, up to 2 MB.",
  imageError: "Choose a JPEG, PNG or WebP image smaller than 2 MB.",
  removeImage: "Remove photo",
  preview: "Campaign preview",
  untitled: "Your campaign",
  noChannels: "No channels selected",
  selectedChannels: "Selected channels",
  updated: "Updated",
  edit: "Edit draft",
  unavailable: "Publishing is not connected yet.",
  publishing: "Channel publishing",
  retry: "Try again",
  loadError: "We couldn’t load campaigns.",
  next: "Next step",
  campaignNext: "Connect your channels before publishing.",
  manageChannels: "Manage integrations",
  plan: "Plan",
  planPlaceholder: "Plan {id}",
  demoPlan: "Sample plan",
  titles: {
    customers: "Build relationships, one customer at a time.",
    loyalty: "Give every visit a reason to lead to the next.",
    memberships: "Make regular visits part of the relationship.",
    offers: "The right offer. The next visit.",
    automations: "Keep the relationship moving.",
    integrations: "One idea. The places your customers are.",
    settings: "Your business, in MemberFlow.",
  },
  descriptions: {
    customers:
      "Customer profiles and activity will appear here after people connect to your business.",
    loyalty:
      "Your loyalty programs will bring stamps, points and rewards into the customer experience.",
    memberships:
      "Manage memberships and prepaid packages together with your customer relationships.",
    offers:
      "Personal offers belong to the same flow as your campaigns and customer activity.",
    automations:
      "Return journeys will use real customer history and agreed triggers. No messages are sent from this preview.",
    integrations:
      "Social channels bring people in. Customer profiles and Wallet keep the connection.",
    settings: "The business details from your setup, all in one place.",
  },
  empty: {
    customers: "No customers connected yet",
    loyalty: "No loyalty programs yet",
    memberships: "No memberships yet",
    offers: "No personal offers yet",
    automations: "No return journeys yet",
  },
  connectionTitle: "Start with customer connection",
  connectionText:
    "Business QR → Customer profile → Apple Wallet / Google Wallet. QR and digital cards will become available after connection setup.",
  loyaltyParts: ["Stamps", "Points", "Rewards"],
  membershipParts: ["Memberships", "Prepaid visits", "Usage history"],
  offerParts: ["Personal offer", "Customer", "Next visit"],
  automationParts: ["Customer history", "Trigger", "Offer", "Next visit"],
  noPrograms: "Configuration will be available in the next product stage.",
  channelsTitle: "Acquisition channels",
  walletTitle: "Customer connection",
  plannedConnection: "Connection setup is not available yet.",
  readOnly:
    "Business details are shown from your setup. Editing is coming next.",
  businessName: "Business name",
  businessType: "Business type",
  city: "City",
  goals: "Your goals",
  owner: "Account",
  role: "Business role",
  billing: "Plan and billing",
  billingText:
    "The chosen plan is a preview selection. Subscription details will appear after activation.",
  noDetails: "No details available yet.",
  attention: "Customer states",
  activity: "Latest activity",
  overview: "Open overview",
  planned: "Not connected yet",
  noActivity: "Activity appears after customers start connecting.",
  unknown: "Not supplied",
};
type Copy = {
  [K in keyof typeof en]: (typeof en)[K] extends string
    ? string
    : (typeof en)[K] extends string[]
      ? string[]
      : { [P in keyof (typeof en)[K]]: string };
};
const ru: Copy = {
  activeFilter: "Активные",
  completedFilter: "Завершённые",
  openCampaign: "Открыть кампанию",
  created: "Создано",
  campaignIntro: "Создайте идею один раз. Подготовьте её для каждого канала.",
  newCampaign: "Создать кампанию",
  all: "Все кампании",
  drafts: "Черновики",
  search: "Найти кампанию",
  noResults: "Подходящих кампаний нет.",
  emptyTitle: "Следующая кампания начинается с одной идеи.",
  emptyText:
    "Предложение, товар, услуга или событие. Добавьте название, детали и выберите каналы.",
  source: "Создать",
  adapt: "Подготовить",
  distribute: "Распространить",
  sourceText: "Идея вашего бизнеса",
  adaptText: "Контент для каждого канала",
  distributeText: "Публикация в подключённых каналах",
  editorTitle: "Создать кампанию",
  editTitle: "Детали кампании",
  title: "Название кампании",
  kind: "Что вы продвигаете?",
  kinds: {
    offer: "Предложение",
    product: "Товар",
    service: "Услуга",
    event: "Событие",
    announcement: "Объявление",
  },
  description: "Описание",
  descriptionHint: "Что должны знать ваши клиенты?",
  price: "Цена (необязательно)",
  currency: "Валюта",
  channels: "Каналы распространения",
  channelsHint:
    "Выберите каналы для подготовки. Это не подключает аккаунты и не публикует контент.",
  save: "Сохранить черновик",
  saving: "Сохраняем…",
  cancel: "Отмена",
  saved: "Черновик сохранён.",
  draftNotice:
    "В этом предпросмотре черновики сохраняются только в текущей вкладке браузера. Ничего не публикуется.",
  apiNotice: "Сохранение кампаний станет доступно после подключения backend.",
  saveError: "Не удалось сохранить черновик. Попробуйте снова.",
  required: "Введите название кампании.",
  image: "Фото кампании (необязательно)",
  imageHint: "JPEG, PNG или WebP, до 2 МБ.",
  imageError: "Выберите JPEG, PNG или WebP размером до 2 МБ.",
  removeImage: "Убрать фото",
  preview: "Предпросмотр кампании",
  untitled: "Ваша кампания",
  noChannels: "Каналы не выбраны",
  selectedChannels: "Выбранные каналы",
  updated: "Обновлено",
  edit: "Редактировать черновик",
  unavailable: "Публикация пока не подключена.",
  publishing: "Публикация по каналам",
  retry: "Попробовать снова",
  loadError: "Не удалось загрузить кампании.",
  next: "Следующий шаг",
  campaignNext: "Подключите каналы перед публикацией.",
  manageChannels: "Управлять интеграциями",
  plan: "Тариф",
  planPlaceholder: "Тариф {id}",
  demoPlan: "Пример тарифа",
  titles: {
    customers: "Отношения начинаются с клиента.",
    loyalty: "Каждый визит — повод прийти снова.",
    memberships: "Постоянные визиты становятся частью отношений.",
    offers: "Нужное предложение. Следующий визит.",
    automations: "Помогайте отношениям продолжаться.",
    integrations: "Одна идея. Там, где ваши клиенты.",
    settings: "Ваш бизнес в MemberFlow.",
  },
  descriptions: {
    customers:
      "Профили и активность появятся здесь, когда клиенты подключатся к бизнесу.",
    loyalty: "Отметки, баллы и награды станут частью клиентского опыта.",
    memberships:
      "Управляйте абонементами и пакетами посещений в контексте отношений с клиентами.",
    offers:
      "Личные предложения продолжают тот же путь, что кампании и клиентская активность.",
    automations:
      "Возврат клиентов будет основан на реальной истории и заданных условиях. Предпросмотр не отправляет сообщения.",
    integrations:
      "Социальные каналы привлекают людей. Клиентский профиль и Wallet сохраняют связь.",
    settings: "Данные бизнеса из регистрации — в одном месте.",
  },
  empty: {
    customers: "Клиенты ещё не подключились",
    loyalty: "Программ лояльности пока нет",
    memberships: "Абонементов пока нет",
    offers: "Личных предложений пока нет",
    automations: "Сценариев возврата пока нет",
  },
  connectionTitle: "Начните с подключения клиентов",
  connectionText:
    "QR бизнеса → Клиентский профиль → Apple Wallet / Google Wallet. QR и цифровые карты появятся после настройки подключения.",
  loyaltyParts: ["Отметки", "Баллы", "Награды"],
  membershipParts: ["Абонементы", "Пакеты посещений", "История использования"],
  offerParts: ["Личное предложение", "Клиент", "Следующий визит"],
  automationParts: [
    "История клиента",
    "Условие",
    "Предложение",
    "Следующий визит",
  ],
  noPrograms: "Настройка станет доступна на следующем этапе продукта.",
  channelsTitle: "Каналы привлечения",
  walletTitle: "Подключение клиентов",
  plannedConnection: "Настройка подключения пока недоступна.",
  readOnly:
    "Данные показаны из регистрации. Редактирование станет доступно позднее.",
  businessName: "Название бизнеса",
  businessType: "Тип бизнеса",
  city: "Город",
  goals: "Ваши цели",
  owner: "Аккаунт",
  role: "Роль в бизнесе",
  billing: "Тариф и оплата",
  billingText:
    "Выбранный тариф используется для предпросмотра. Данные подписки появятся после активации.",
  noDetails: "Данных пока нет.",
  attention: "Состояния клиентов",
  activity: "Последние события",
  overview: "Открыть обзор",
  planned: "Пока не подключено",
  noActivity: "События появятся после подключения клиентов.",
  unknown: "Не указано",
};
const lv: Copy = {
  activeFilter: "Aktīvās",
  completedFilter: "Pabeigtās",
  openCampaign: "Atvērt kampaņu",
  created: "Izveidota",
  campaignIntro: "Izveidojiet ideju vienreiz. Sagatavojiet to katram kanālam.",
  newCampaign: "Izveidot kampaņu",
  all: "Visas kampaņas",
  drafts: "Melnraksti",
  search: "Atrast kampaņu",
  noResults: "Nav atbilstošu kampaņu.",
  emptyTitle: "Nākamā kampaņa sākas ar vienu ideju.",
  emptyText:
    "Piedāvājums, produkts, pakalpojums vai pasākums. Pievienojiet nosaukumu, detaļas un izvēlieties kanālus.",
  source: "Izveidot",
  adapt: "Sagatavot",
  distribute: "Izplatīt",
  sourceText: "Jūsu uzņēmuma ideja",
  adaptText: "Saturs katram kanālam",
  distributeText: "Publicēšana pievienotajos kanālos",
  editorTitle: "Izveidot kampaņu",
  editTitle: "Kampaņas detaļas",
  title: "Kampaņas nosaukums",
  kind: "Ko jūs reklamējat?",
  kinds: {
    offer: "Piedāvājums",
    product: "Produkts",
    service: "Pakalpojums",
    event: "Pasākums",
    announcement: "Paziņojums",
  },
  description: "Detaļas",
  descriptionHint: "Kas klientiem jāzina?",
  price: "Cena (neobligāti)",
  currency: "Valūta",
  channels: "Izplatīšanas kanāli",
  channelsHint:
    "Izvēlieties kanālus sagatavošanai. Tas nepievieno kontus un nepublicē saturu.",
  save: "Saglabāt melnrakstu",
  saving: "Saglabā…",
  cancel: "Atcelt",
  saved: "Melnraksts saglabāts.",
  draftNotice:
    "Priekšskatījumā melnraksti saglabājas tikai šajā pārlūka cilnē. Nekas netiek publicēts.",
  apiNotice: "Kampaņu saglabāšana būs pieejama pēc backend pievienošanas.",
  saveError: "Neizdevās saglabāt melnrakstu. Mēģiniet vēlreiz.",
  required: "Ievadiet kampaņas nosaukumu.",
  image: "Kampaņas foto (neobligāti)",
  imageHint: "JPEG, PNG vai WebP, līdz 2 MB.",
  imageError: "Izvēlieties JPEG, PNG vai WebP attēlu līdz 2 MB.",
  removeImage: "Noņemt foto",
  preview: "Kampaņas priekšskatījums",
  untitled: "Jūsu kampaņa",
  noChannels: "Nav izvēlētu kanālu",
  selectedChannels: "Izvēlētie kanāli",
  updated: "Atjaunināts",
  edit: "Rediģēt melnrakstu",
  unavailable: "Publicēšana vēl nav pievienota.",
  publishing: "Publicēšana kanālos",
  retry: "Mēģināt vēlreiz",
  loadError: "Neizdevās ielādēt kampaņas.",
  next: "Nākamais solis",
  campaignNext: "Pievienojiet kanālus pirms publicēšanas.",
  manageChannels: "Pārvaldīt integrācijas",
  plan: "Plāns",
  planPlaceholder: "Plāns {id}",
  demoPlan: "Plāna paraugs",
  titles: {
    customers: "Attiecības sākas ar klientu.",
    loyalty: "Katrs apmeklējums ir iemesls nākamajam.",
    memberships: "Regulāri apmeklējumi kļūst par attiecību daļu.",
    offers: "Īstais piedāvājums. Nākamais apmeklējums.",
    automations: "Turpiniet attiecību plūsmu.",
    integrations: "Viena ideja. Tur, kur ir jūsu klienti.",
    settings: "Jūsu uzņēmums MemberFlow.",
  },
  descriptions: {
    customers:
      "Klientu profili un aktivitāte parādīsies, kad cilvēki pievienosies uzņēmumam.",
    loyalty: "Zīmogi, punkti un atlīdzības kļūs par klienta pieredzes daļu.",
    memberships:
      "Pārvaldiet abonementus un apmeklējumu paketes klientu attiecību kontekstā.",
    offers:
      "Personīgie piedāvājumi turpina to pašu plūsmu kā kampaņas un klientu aktivitāte.",
    automations:
      "Atgriešanās ceļi izmantos īstu klientu vēsturi un noteiktus nosacījumus. Priekšskatījums nesūta ziņas.",
    integrations:
      "Sociālie kanāli piesaista cilvēkus. Klienta profils un Wallet saglabā saikni.",
    settings: "Uzņēmuma dati no reģistrācijas vienuviet.",
  },
  empty: {
    customers: "Klienti vēl nav pievienojušies",
    loyalty: "Vēl nav lojalitātes programmu",
    memberships: "Vēl nav abonementu",
    offers: "Vēl nav personīgo piedāvājumu",
    automations: "Vēl nav atgriešanās ceļu",
  },
  connectionTitle: "Sāciet ar klientu savienojumu",
  connectionText:
    "Uzņēmuma QR → Klienta profils → Apple Wallet / Google Wallet. QR un digitālās kartes būs pieejamas pēc savienojuma iestatīšanas.",
  loyaltyParts: ["Zīmogi", "Punkti", "Atlīdzības"],
  membershipParts: [
    "Abonementi",
    "Apmaksāti apmeklējumi",
    "Lietošanas vēsture",
  ],
  offerParts: ["Personīgais piedāvājums", "Klients", "Nākamais apmeklējums"],
  automationParts: [
    "Klienta vēsture",
    "Nosacījums",
    "Piedāvājums",
    "Nākamais apmeklējums",
  ],
  noPrograms: "Iestatīšana būs pieejama nākamajā produkta posmā.",
  channelsTitle: "Piesaistes kanāli",
  walletTitle: "Klientu savienojums",
  plannedConnection: "Savienojuma iestatīšana vēl nav pieejama.",
  readOnly: "Dati parādīti no reģistrācijas. Rediģēšana būs pieejama vēlāk.",
  businessName: "Uzņēmuma nosaukums",
  businessType: "Uzņēmuma veids",
  city: "Pilsēta",
  goals: "Jūsu mērķi",
  owner: "Konts",
  role: "Loma uzņēmumā",
  billing: "Plāns un norēķini",
  billingText:
    "Izvēlētais plāns izmantots priekšskatījumam. Abonementa dati parādīsies pēc aktivizācijas.",
  noDetails: "Dati vēl nav pieejami.",
  attention: "Klientu stāvokļi",
  activity: "Jaunākie notikumi",
  overview: "Atvērt pārskatu",
  planned: "Vēl nav pievienots",
  noActivity: "Aktivitāte parādīsies pēc klientu pievienošanās.",
  unknown: "Nav norādīts",
};
export const workspaceContent: Record<Locale, Copy> = { en, lv, ru };
export type WorkspaceContent = Copy;
