import type { Locale } from "@/content";
const en = {
  access: "Staff workspace",
  scan: "Scan customer",
  scanHint: "Scan the customer’s QR code.",
  startCamera: "Open camera",
  stopCamera: "Stop camera",
  manual: "Enter code manually",
  code: "Customer code",
  resolve: "Find customer",
  resolving: "Finding customer…",
  recent: "Recent actions",
  noRecent: "Actions recorded by the backend will appear here.",
  customerSince: "Customer since",
  loyalty: "Loyalty",
  stamps: "Stamps",
  nextReward: "Next reward",
  membership: "Membership",
  remaining: "{n} visits remaining",
  available: "Available actions",
  back: "Scan another customer",
  confirm: "Confirm",
  cancel: "Cancel",
  close: "Close",
  working: "Recording…",
  remainingAfter: "Remaining after action: {n}",
  loadError: "We couldn’t load your staff workspace.",
  retry: "Try again",
  accessDenied: "Scanning access is unavailable for this business.",
  resolveError:
    "We couldn’t resolve this customer. Check the code and try again.",
  actionError: "The action could not be recorded. Please try again.",
  previewNotice:
    "Customer actions require the Symfony API. This preview does not record visits or change balances.",
  noActions: "No actions available for this customer.",
  logout: "Log out",
  logoutError: "The session service is unavailable. Try again later.",
  states: {
    idle: "Ready to scan",
    requesting: "Waiting for camera access…",
    scanning: "Place the QR code inside the frame",
    denied:
      "Camera access was denied. Allow it in your browser settings or enter the code manually.",
    unsupported:
      "Camera QR scanning is unavailable in this browser. Enter the customer code manually.",
    notFound: "No camera was found. Enter the customer code manually.",
    error: "We couldn’t open the camera. Try again or enter the code manually.",
  },
  actions: {
    VISIT_CREATED: "Add visit",
    STAMP_ADDED: "Add stamp",
    SUBSCRIPTION_USED: "Use membership visit",
    REWARD_REDEEMED: "Redeem reward",
    OFFER_REDEEMED: "Redeem offer",
  },
  confirmations: {
    VISIT_CREATED: "Record this customer’s visit?",
    STAMP_ADDED: "Add a loyalty stamp?",
    SUBSCRIPTION_USED: "Use one membership visit?",
    REWARD_REDEEMED: "Redeem this reward?",
    OFFER_REDEEMED: "Redeem this offer?",
  },
  success: {
    VISIT_CREATED: "Visit added",
    STAMP_ADDED: "Stamp added",
    SUBSCRIPTION_USED: "Membership visit used",
    REWARD_REDEEMED: "Reward redeemed",
    OFFER_REDEEMED: "Offer redeemed",
  },
};
export type StaffContent = {
  [K in keyof typeof en]: (typeof en)[K] extends string
    ? string
    : { [P in keyof (typeof en)[K]]: string };
};
const ru: StaffContent = {
  access: "Рабочее место сотрудника",
  scan: "Сканировать клиента",
  scanHint: "Отсканируйте QR клиента.",
  startCamera: "Открыть камеру",
  stopCamera: "Остановить камеру",
  manual: "Ввести код вручную",
  code: "Код клиента",
  resolve: "Найти клиента",
  resolving: "Ищем клиента…",
  recent: "Последние действия",
  noRecent: "Здесь появятся действия, записанные backend.",
  customerSince: "Клиент с",
  loyalty: "Лояльность",
  stamps: "Отметки",
  nextReward: "Следующая награда",
  membership: "Абонемент",
  remaining: "Осталось посещений: {n}",
  available: "Доступные действия",
  back: "Сканировать другого клиента",
  confirm: "Подтвердить",
  cancel: "Отмена",
  close: "Закрыть",
  working: "Записываем…",
  remainingAfter: "После операции останется: {n}",
  loadError: "Не удалось загрузить рабочее место сотрудника.",
  retry: "Повторить",
  accessDenied: "Сканирование недоступно для вашего доступа в этом бизнесе.",
  resolveError: "Не удалось найти клиента. Проверьте код и повторите попытку.",
  actionError: "Не удалось записать действие. Попробуйте ещё раз.",
  previewNotice:
    "Действия с клиентами требуют Symfony API. Превью не записывает визиты и не меняет баланс.",
  noActions: "Для этого клиента нет доступных действий.",
  logout: "Выйти",
  logoutError: "Сервис сессий недоступен. Попробуйте позже.",
  states: {
    idle: "Готово к сканированию",
    requesting: "Ожидаем доступ к камере…",
    scanning: "Поместите QR внутри рамки",
    denied:
      "Нет доступа к камере. Разрешите его в настройках браузера или введите код вручную.",
    unsupported:
      "QR-сканирование камерой недоступно в этом браузере. Введите код клиента вручную.",
    notFound: "Камера не найдена. Введите код клиента вручную.",
    error:
      "Не удалось открыть камеру. Попробуйте ещё раз или введите код вручную.",
  },
  actions: {
    VISIT_CREATED: "Добавить посещение",
    STAMP_ADDED: "Добавить штамп",
    SUBSCRIPTION_USED: "Использовать посещение",
    REWARD_REDEEMED: "Выдать награду",
    OFFER_REDEEMED: "Погасить предложение",
  },
  confirmations: {
    VISIT_CREATED: "Записать посещение клиента?",
    STAMP_ADDED: "Добавить штамп лояльности?",
    SUBSCRIPTION_USED: "Использовать одно посещение по абонементу?",
    REWARD_REDEEMED: "Выдать эту награду?",
    OFFER_REDEEMED: "Погасить это предложение?",
  },
  success: {
    VISIT_CREATED: "Посещение добавлено",
    STAMP_ADDED: "Штамп добавлен",
    SUBSCRIPTION_USED: "Посещение использовано",
    REWARD_REDEEMED: "Награда выдана",
    OFFER_REDEEMED: "Предложение погашено",
  },
};
const lv: StaffContent = {
  access: "Darbinieka darba vieta",
  scan: "Skenēt klientu",
  scanHint: "Noskenējiet klienta QR kodu.",
  startCamera: "Atvērt kameru",
  stopCamera: "Apturēt kameru",
  manual: "Ievadīt kodu manuāli",
  code: "Klienta kods",
  resolve: "Atrast klientu",
  resolving: "Meklē klientu…",
  recent: "Pēdējās darbības",
  noRecent: "Šeit parādīsies serverī reģistrētās darbības.",
  customerSince: "Klients kopš",
  loyalty: "Lojalitāte",
  stamps: "Zīmogi",
  nextReward: "Nākamā atlīdzība",
  membership: "Abonements",
  remaining: "Atlikuši {n} apmeklējumi",
  available: "Pieejamās darbības",
  back: "Skenēt citu klientu",
  confirm: "Apstiprināt",
  cancel: "Atcelt",
  close: "Aizvērt",
  working: "Reģistrē…",
  remainingAfter: "Pēc darbības atliks: {n}",
  loadError: "Neizdevās ielādēt darbinieka darba vietu.",
  retry: "Mēģināt vēlreiz",
  accessDenied: "Jūsu piekļuve šim uzņēmumam neļauj skenēt klientus.",
  resolveError:
    "Neizdevās atrast klientu. Pārbaudiet kodu un mēģiniet vēlreiz.",
  actionError: "Neizdevās reģistrēt darbību. Mēģiniet vēlreiz.",
  previewNotice:
    "Klientu darbībām nepieciešams Symfony API. Priekšskatījums nereģistrē apmeklējumus un nemaina atlikumus.",
  noActions: "Šim klientam nav pieejamu darbību.",
  logout: "Izrakstīties",
  logoutError: "Sesiju pakalpojums nav pieejams. Mēģiniet vēlāk.",
  states: {
    idle: "Gatavs skenēšanai",
    requesting: "Gaida kameras piekļuvi…",
    scanning: "Novietojiet QR kodu rāmī",
    denied:
      "Kameras piekļuve liegta. Atļaujiet to pārlūka iestatījumos vai ievadiet kodu manuāli.",
    unsupported:
      "Šajā pārlūkā nav pieejama QR skenēšana ar kameru. Ievadiet klienta kodu manuāli.",
    notFound: "Kamera nav atrasta. Ievadiet klienta kodu manuāli.",
    error:
      "Neizdevās atvērt kameru. Mēģiniet vēlreiz vai ievadiet kodu manuāli.",
  },
  actions: {
    VISIT_CREATED: "Pievienot apmeklējumu",
    STAMP_ADDED: "Pievienot zīmogu",
    SUBSCRIPTION_USED: "Izmantot apmeklējumu",
    REWARD_REDEEMED: "Izsniegt atlīdzību",
    OFFER_REDEEMED: "Izmantot piedāvājumu",
  },
  confirmations: {
    VISIT_CREATED: "Reģistrēt klienta apmeklējumu?",
    STAMP_ADDED: "Pievienot lojalitātes zīmogu?",
    SUBSCRIPTION_USED: "Izmantot vienu abonementa apmeklējumu?",
    REWARD_REDEEMED: "Izsniegt šo atlīdzību?",
    OFFER_REDEEMED: "Izmantot šo piedāvājumu?",
  },
  success: {
    VISIT_CREATED: "Apmeklējums pievienots",
    STAMP_ADDED: "Zīmogs pievienots",
    SUBSCRIPTION_USED: "Apmeklējums izmantots",
    REWARD_REDEEMED: "Atlīdzība izsniegta",
    OFFER_REDEEMED: "Piedāvājums izmantots",
  },
};
export const staffContent: Record<Locale, StaffContent> = { en, lv, ru };
