import type { Locale } from "@/content";
const en = {
  accessDenied: "Access unavailable",
  accessDeniedText:
    "Your business membership does not grant access to this section.",
  greeting: "Good day, {name}.",
  setupFlowCopy: [
    "Create your first campaign",
    "Set up your business QR",
    "Create loyalty or a membership",
    "Available after customer history",
  ],
  waiting: "Waiting for customer history",
  statusHeading: "MemberFlow status",
  connectionReady: "{ready} / {total} ready",
  needsSetup: "Needs setup",
  retentionLabel: "Retention",
  channelsLabel: "Channels",
  channelsConnected: "{n} connected",
  noChannels: "No channels connected",
  retentionCount: "{n} active",
  setupCount: "{done} of {total} setup steps ready",
  viewSetup: "View setup",
  continueSetup: "Continue setup",
  periodDays: "Last {n} days",
  allQuiet: "Everything is up to date.",
  allQuietText: "Review customer activity or prepare your next campaign.",
  operationalCampaignTitle: "Prepare your next campaign",
  operationalCampaignText:
    "Create a new offer, product or event for your customers.",
  reviewCampaignTitle: "Review campaign publishing",
  reviewCampaignText:
    "Check the channel statuses and continue from your campaign.",
  returnOfferText:
    "Customers are marked inactive. Prepare an offer to reconnect with them.",
  activityHeading: "Latest activity",
  createActions: {
    campaigns: "Create campaign",
    offers: "Create offer",
    customers: "Add customer",
    loyalty: "Create loyalty program",
    memberships: "Create membership",
  },
  eventCopy: {
    CUSTOMER_JOINED: "joined your business",
    QR_SCANNED: "scanned your business QR",
    VISIT_CREATED: "completed a visit",
    STAMP_ADDED: "received a loyalty stamp",
    REWARD_EARNED: "earned a reward",
    REWARD_REDEEMED: "redeemed a reward",
    SUBSCRIPTION_USED: "used a membership visit",
    OFFER_REDEEMED: "redeemed an offer",
    CUSTOMER_RETURNED: "returned to your business",
  },
  nav: {
    billing: "Plan and usage",
    team: "Team",
    overview: "Overview",
    campaigns: "Campaigns",
    offers: "Offers",
    customers: "Customers",
    "customer-page": "Customer Page",
    loyalty: "Loyalty",
    memberships: "Memberships",
    automations: "Automations",
    integrations: "Integrations",
    settings: "Settings",
  },
  groups: ["Grow", "Customers", "Engage", "Management"],
  roles: { OWNER: "Owner", ADMIN: "Admin", MANAGER: "Manager", STAFF: "Staff" },
  category: {
    cafe: "Café & Restaurant",
    beauty: "Beauty & Wellness",
    fitness: "Fitness & Gym",
    retail: "Retail",
    services: "Services",
    other: "Other",
  },
  business: "Your business",
  switchBusiness: "Switch business",
  profile: "Profile",
  billing: "Billing",
  logout: "Log out",
  logoutError: "Session service is unavailable. Please try again later.",
  menu: "Open navigation",
  close: "Close",
  collapse: "Collapse sidebar",
  expand: "Expand sidebar",
  create: "Create",
  planned: "Coming next",
  notifications: "Notifications",
  noNotifications: "No new notifications.",
  welcome: "Welcome to MemberFlow, {name}.",
  ready: "Your business is ready for its next step.",
  dismiss: "Dismiss welcome",
  heading: "Your business. One flow.",
  intro:
    "A place to reach new people, build relationships and keep them coming back.",
  demo: "Sample workspace — illustrative data, not your live business.",
  setup: "Setup flow",
  stages: ["Business", "Reach", "Connect", "Return"],
  flowStages: ["Reach", "Connect", "Retain", "Return"],
  complete: "Ready",
  next: "Next",
  pending: "Not set up",
  stepsHeading: "Let’s get your flow moving.",
  stepsText: "Start with what matters to your business. The rest follows.",
  actions: {
    campaigns: [
      "Create your first campaign",
      "Turn an offer, product or event into content.",
      "Create campaign",
    ],
    customers: [
      "Connect your customers",
      "Prepare your business QR and customer experience.",
      "Set up connection",
    ],
    loyalty: [
      "Give them a reason to return",
      "Build a loyalty experience for your customers.",
      "Set up loyalty",
    ],
    memberships: [
      "Create a membership",
      "Give regular customers a place to belong.",
      "Set up membership",
    ],
    integrations: [
      "Connect a channel",
      "Prepare the places where people discover you.",
      "View integrations",
    ],
    offers: [
      "Prepare a return offer",
      "Reconnect with customers who have stopped visiting.",
      "View offers",
    ],
  },
  later:
    "Return journeys become useful once you start building customer history.",
  nextAction: "Your next step",
  flow: "Customer flow",
  metrics: [
    "Campaign views",
    "New customers",
    "Returning customers",
    "Reactivated customers",
  ],
  noMetric: "Not available",
  campaigns: "Active campaigns",
  noCampaigns: "No campaigns yet.",
  campaignEmpty:
    "Create an offer once and prepare it for the channels where customers discover you.",
  viewCampaign: "View campaign",
  started: "Started",
  statuses: {
    DRAFT: "Draft",
    PROCESSING: "Publishing…",
    PUBLISHED: "Published",
    PARTIALLY_PUBLISHED: "Partially published",
    FAILED: "Publishing failed",
    COMPLETED: "Completed",
    PAUSED: "Paused",
  },
  activity: "Customer activity",
  noActivity: "Your relationships start here.",
  activityEmpty:
    "Activity will appear after people connect through your business QR or customer experience.",
  viewCustomers: "View customers",
  events: {
    joined: "joined your business",
    visit: "completed a visit",
    reward: "earned a reward",
    membership: "used a membership visit",
    redemption: "redeemed an offer",
  },
  attention: "Needs attention",
  noAttention: "No attention states to show.",
  attentionReasons: {
    inactive: "Last visit {n} days ago",
    expiring: "Membership expires in {n} days",
    rewardNear: "{n} stamp(s) away from a reward",
  },
  retention: "Reasons to return",
  active: "Active",
  noRetention: "No retention tools set up yet.",
  connection: "Customer connection",
  connections: {
    qr: "Business QR",
    profile: "Customer profile",
    apple: "Apple Wallet",
    google: "Google Wallet",
  },
  integrationHeading: "Channels",
  manage: "Manage integrations",
  configure: "Configure",
  connectionStatuses: {
    ready: "Ready",
    connected: "Connected",
    notConfigured: "Not configured",
    processing: "Processing",
    failed: "Needs attention",
  },
  error: "We couldn’t load your overview.",
  errorText:
    "Your workspace navigation is still available. Try again when the connection is restored.",
  retry: "Try again",
  loading: "Loading your workspace",
  shellTitle: "The next part of your flow.",
  shellText:
    "This workspace is prepared for the next stage of MemberFlow. The feature is not available yet.",
  back: "Back to overview",
  noBusiness: "MemberFlow workspace",
  planPending: "Plan not supplied",
  noUser: "Your account",
  account: "Account",
  businessSettings: "Business settings",
  billingShell: "Plan and billing details will come from the billing service.",
  profileShell:
    "Your account profile will come from the authentication service.",
  selected: "Current business",
  availableAfter: "Available after setup",
};
type Strings = {
  [K in keyof typeof en]: (typeof en)[K] extends string
    ? string
    : (typeof en)[K] extends string[]
      ? string[]
      : {
          [P in keyof (typeof en)[K]]: (typeof en)[K][P] extends string[]
            ? string[]
            : string;
        };
};
const ru: Strings = {
  accessDenied: "Раздел недоступен",
  accessDeniedText: "Ваш доступ в этом бизнесе не включает этот раздел.",
  greeting: "Добрый день, {name}.",
  setupFlowCopy: [
    "Создайте первую кампанию",
    "Настройте QR бизнеса",
    "Создайте лояльность или абонемент",
    "Появится после истории клиентов",
  ],
  waiting: "Ожидает истории клиентов",
  statusHeading: "Состояние MemberFlow",
  connectionReady: "{ready} / {total} готово",
  needsSetup: "Требует настройки",
  retentionLabel: "Удержание",
  channelsLabel: "Каналы",
  channelsConnected: "Подключено: {n}",
  noChannels: "Нет подключённых каналов",
  retentionCount: "Активных: {n}",
  setupCount: "Настроено шагов: {done} из {total}",
  viewSetup: "Посмотреть настройку",
  continueSetup: "Продолжить настройку",
  periodDays: "Последние {n} дней",
  allQuiet: "Всё спокойно.",
  allQuietText:
    "Посмотрите активность клиентов или подготовьте следующую кампанию.",
  operationalCampaignTitle: "Подготовьте следующую кампанию",
  operationalCampaignText:
    "Создайте новое предложение, товар или событие для клиентов.",
  reviewCampaignTitle: "Проверьте публикацию кампании",
  reviewCampaignText:
    "Посмотрите состояния каналов и продолжите работу с кампанией.",
  returnOfferText:
    "Есть клиенты со статусом «неактивен». Подготовьте предложение, чтобы восстановить связь.",
  activityHeading: "Последняя активность",
  createActions: {
    campaigns: "Создать кампанию",
    offers: "Создать предложение",
    customers: "Добавить клиента",
    loyalty: "Создать программу лояльности",
    memberships: "Создать абонемент",
  },
  eventCopy: {
    CUSTOMER_JOINED: "подключился к бизнесу",
    QR_SCANNED: "отсканировал QR бизнеса",
    VISIT_CREATED: "завершил посещение",
    STAMP_ADDED: "получил отметку лояльности",
    REWARD_EARNED: "получил награду",
    REWARD_REDEEMED: "использовал награду",
    SUBSCRIPTION_USED: "использовал посещение по абонементу",
    OFFER_REDEEMED: "воспользовался предложением",
    CUSTOMER_RETURNED: "вернулся в ваш бизнес",
  },
  nav: {
    billing: "Тариф и использование",
    team: "Команда",
    overview: "Обзор",
    campaigns: "Кампании",
    offers: "Предложения",
    customers: "Клиенты",
    "customer-page": "Клиентская страница",
    loyalty: "Лояльность",
    memberships: "Абонементы",
    automations: "Автоматизации",
    integrations: "Интеграции",
    settings: "Настройки",
  },
  groups: ["Привлечение", "Клиенты", "Взаимодействие", "Управление"],
  roles: {
    OWNER: "Владелец",
    ADMIN: "Администратор",
    MANAGER: "Менеджер",
    STAFF: "Сотрудник",
  },
  category: {
    cafe: "Кафе и рестораны",
    beauty: "Красота и здоровье",
    fitness: "Фитнес и спорт",
    retail: "Розничная торговля",
    services: "Услуги",
    other: "Другое",
  },
  business: "Ваш бизнес",
  switchBusiness: "Выбрать бизнес",
  profile: "Профиль",
  billing: "Оплата и тариф",
  logout: "Выйти",
  logoutError: "Сервис сессий недоступен. Попробуйте позже.",
  menu: "Открыть навигацию",
  close: "Закрыть",
  collapse: "Свернуть меню",
  expand: "Развернуть меню",
  create: "Создать",
  planned: "В разработке",
  notifications: "Уведомления",
  noNotifications: "Новых уведомлений нет.",
  welcome: "Добро пожаловать в MemberFlow, {name}.",
  ready: "Ваш бизнес готов к следующему шагу.",
  dismiss: "Закрыть приветствие",
  heading: "Ваш бизнес. Единый поток.",
  intro:
    "Привлекайте людей, стройте отношения и помогайте клиентам возвращаться.",
  demo: "Пример рабочего пространства — демонстрационные данные, а не ваш бизнес.",
  setup: "Начало вашего потока",
  stages: ["Бизнес", "Охват", "Связь", "Возврат"],
  flowStages: ["Охват", "Связь", "Удержание", "Возврат"],
  complete: "Готово",
  next: "Следующий шаг",
  pending: "Не настроено",
  stepsHeading: "Запустим ваш поток.",
  stepsText:
    "Начните с того, что важно вашему бизнесу. Остальное — следующий шаг.",
  actions: {
    campaigns: [
      "Создайте первую кампанию",
      "Превратите предложение, товар или событие в контент.",
      "Создать кампанию",
    ],
    customers: [
      "Подключите клиентов",
      "Подготовьте QR бизнеса и клиентский профиль.",
      "Настроить подключение",
    ],
    loyalty: [
      "Дайте повод вернуться",
      "Создайте программу лояльности для клиентов.",
      "Настроить лояльность",
    ],
    memberships: [
      "Создайте абонемент",
      "Дайте постоянным клиентам больше возможностей.",
      "Настроить абонемент",
    ],
    integrations: [
      "Подключите канал",
      "Подготовьте площадки, где вас находят новые люди.",
      "Смотреть интеграции",
    ],
    offers: [
      "Подготовьте предложение для возврата",
      "Восстановите связь с клиентами, которые давно не заходили.",
      "Смотреть предложения",
    ],
  },
  later: "Возврат клиентов станет доступен, когда появится история посещений.",
  nextAction: "Следующий шаг",
  flow: "Поток клиентов",
  metrics: [
    "Просмотры кампаний",
    "Новые клиенты",
    "Вернувшиеся клиенты",
    "Возвращённые клиенты",
  ],
  noMetric: "Нет данных",
  campaigns: "Активные кампании",
  noCampaigns: "Кампаний пока нет.",
  campaignEmpty:
    "Создайте предложение один раз и подготовьте его для каналов привлечения.",
  viewCampaign: "Смотреть кампанию",
  started: "Начало",
  statuses: {
    DRAFT: "Черновик",
    PROCESSING: "Публикуется…",
    PUBLISHED: "Опубликовано",
    PARTIALLY_PUBLISHED: "Частично опубликовано",
    FAILED: "Ошибка публикации",
    COMPLETED: "Завершено",
    PAUSED: "Приостановлено",
  },
  activity: "Активность клиентов",
  noActivity: "Здесь начинаются отношения.",
  activityEmpty:
    "Активность появится, когда клиенты подключатся через QR или клиентский профиль.",
  viewCustomers: "Смотреть клиентов",
  events: {
    joined: "подключился к бизнесу",
    visit: "завершил посещение",
    reward: "получил награду",
    membership: "использовал посещение по абонементу",
    redemption: "воспользовался предложением",
  },
  attention: "Требует внимания",
  noAttention: "Нет состояний, требующих внимания.",
  attentionReasons: {
    inactive: "Последнее посещение {n} дн. назад",
    expiring: "Абонемент истекает через {n} дн.",
    rewardNear: "До награды осталось отметок: {n}",
  },
  retention: "Поводы вернуться",
  active: "Активных",
  noRetention: "Инструменты удержания ещё не настроены.",
  connection: "Подключение клиентов",
  connections: {
    qr: "QR бизнеса",
    profile: "Клиентский профиль",
    apple: "Apple Wallet",
    google: "Google Wallet",
  },
  integrationHeading: "Каналы",
  manage: "Управлять интеграциями",
  configure: "Настроить",
  connectionStatuses: {
    ready: "Готово",
    connected: "Подключено",
    notConfigured: "Не настроено",
    processing: "Обработка",
    failed: "Требует внимания",
  },
  error: "Не удалось загрузить обзор.",
  errorText:
    "Навигация доступна. Попробуйте снова, когда соединение восстановится.",
  retry: "Попробовать снова",
  loading: "Загружаем рабочее пространство",
  shellTitle: "Следующий этап вашего потока.",
  shellText:
    "Раздел подготовлен для следующего этапа MemberFlow. Функция пока недоступна.",
  back: "Вернуться к обзору",
  noBusiness: "Рабочее пространство MemberFlow",
  planPending: "Тариф не указан",
  noUser: "Ваш аккаунт",
  account: "Аккаунт",
  businessSettings: "Настройки бизнеса",
  billingShell: "Тариф и платёжные данные будут получены от сервиса оплаты.",
  profileShell: "Данные профиля будут получены от сервиса авторизации.",
  selected: "Текущий бизнес",
  availableAfter: "После настройки",
};
const lv: Strings = {
  accessDenied: "Sadaļa nav pieejama",
  accessDeniedText: "Jūsu piekļuve šim uzņēmumam neietver šo sadaļu.",
  greeting: "Labdien, {name}.",
  setupFlowCopy: [
    "Izveidojiet pirmo kampaņu",
    "Iestatiet uzņēmuma QR",
    "Izveidojiet lojalitāti vai abonementu",
    "Pieejams pēc klientu vēstures izveides",
  ],
  waiting: "Gaida klientu vēsturi",
  statusHeading: "MemberFlow stāvoklis",
  connectionReady: "{ready} / {total} gatavi",
  needsSetup: "Jāiestata",
  retentionLabel: "Noturēšana",
  channelsLabel: "Kanāli",
  channelsConnected: "Savienoti: {n}",
  noChannels: "Nav savienotu kanālu",
  retentionCount: "Aktīvi: {n}",
  setupCount: "Iestatīti {done} no {total} soļiem",
  viewSetup: "Skatīt iestatījumus",
  continueSetup: "Turpināt iestatīšanu",
  periodDays: "Pēdējās {n} dienas",
  allQuiet: "Viss ir kārtībā.",
  allQuietText: "Skatiet klientu aktivitāti vai sagatavojiet nākamo kampaņu.",
  operationalCampaignTitle: "Sagatavojiet nākamo kampaņu",
  operationalCampaignText:
    "Izveidojiet klientiem jaunu piedāvājumu, produktu vai pasākumu.",
  reviewCampaignTitle: "Pārskatiet kampaņas publicēšanu",
  reviewCampaignText:
    "Pārbaudiet kanālu stāvokļus un turpiniet darbu ar kampaņu.",
  returnOfferText:
    "Dažiem klientiem ir neaktīvs statuss. Sagatavojiet piedāvājumu, lai atjaunotu saikni.",
  activityHeading: "Jaunākā aktivitāte",
  createActions: {
    campaigns: "Izveidot kampaņu",
    offers: "Izveidot piedāvājumu",
    customers: "Pievienot klientu",
    loyalty: "Izveidot lojalitātes programmu",
    memberships: "Izveidot abonementu",
  },
  eventCopy: {
    CUSTOMER_JOINED: "pievienojās uzņēmumam",
    QR_SCANNED: "noskenēja uzņēmuma QR",
    VISIT_CREATED: "pabeidza apmeklējumu",
    STAMP_ADDED: "saņēma lojalitātes zīmogu",
    REWARD_EARNED: "ieguva atlīdzību",
    REWARD_REDEEMED: "izmantoja atlīdzību",
    SUBSCRIPTION_USED: "izmantoja abonementa apmeklējumu",
    OFFER_REDEEMED: "izmantoja piedāvājumu",
    CUSTOMER_RETURNED: "atgriezās uzņēmumā",
  },
  nav: {
    billing: "Plāns un lietojums",
    team: "Komanda",
    overview: "Pārskats",
    campaigns: "Kampaņas",
    offers: "Piedāvājumi",
    customers: "Klienti",
    "customer-page": "Klienta lapa",
    loyalty: "Lojalitāte",
    memberships: "Abonementi",
    automations: "Automatizācija",
    integrations: "Integrācijas",
    settings: "Iestatījumi",
  },
  groups: ["Izaugsme", "Klienti", "Iesaistīšana", "Pārvaldība"],
  roles: {
    OWNER: "Īpašnieks",
    ADMIN: "Administrators",
    MANAGER: "Vadītājs",
    STAFF: "Darbinieks",
  },
  category: {
    cafe: "Kafejnīcas un restorāni",
    beauty: "Skaistums un labsajūta",
    fitness: "Fitness un sports",
    retail: "Mazumtirdzniecība",
    services: "Pakalpojumi",
    other: "Cits",
  },
  business: "Jūsu uzņēmums",
  switchBusiness: "Izvēlēties uzņēmumu",
  profile: "Profils",
  billing: "Norēķini",
  logout: "Izrakstīties",
  logoutError: "Sesiju pakalpojums nav pieejams. Mēģiniet vēlāk.",
  menu: "Atvērt navigāciju",
  close: "Aizvērt",
  collapse: "Sakļaut izvēlni",
  expand: "Izvērst izvēlni",
  create: "Izveidot",
  planned: "Drīzumā",
  notifications: "Paziņojumi",
  noNotifications: "Nav jaunu paziņojumu.",
  welcome: "Laipni lūdzam MemberFlow, {name}.",
  ready: "Jūsu uzņēmums ir gatavs nākamajam solim.",
  dismiss: "Aizvērt sveicienu",
  heading: "Jūsu uzņēmums. Viena plūsma.",
  intro:
    "Sasniedziet jaunus cilvēkus, veidojiet attiecības un palīdziet klientiem atgriezties.",
  demo: "Darba telpas paraugs — ilustratīvi dati, nevis jūsu uzņēmums.",
  setup: "Iestatīšanas plūsma",
  stages: ["Uzņēmums", "Sasniedziet", "Savienojiet", "Atgrieziet"],
  flowStages: ["Sasniedziet", "Savienojiet", "Noturiet", "Atgrieziet"],
  complete: "Gatavs",
  next: "Nākamais solis",
  pending: "Nav iestatīts",
  stepsHeading: "Iekustināsim jūsu plūsmu.",
  stepsText: "Sāciet ar uzņēmumam svarīgāko. Pārējais sekos.",
  actions: {
    campaigns: [
      "Izveidojiet pirmo kampaņu",
      "Pārvērtiet piedāvājumu, produktu vai pasākumu saturā.",
      "Izveidot kampaņu",
    ],
    customers: [
      "Savienojiet savus klientus",
      "Sagatavojiet uzņēmuma QR un klienta pieredzi.",
      "Iestatīt savienojumu",
    ],
    loyalty: [
      "Dodiet iemeslu atgriezties",
      "Izveidojiet klientu lojalitātes pieredzi.",
      "Iestatīt lojalitāti",
    ],
    memberships: [
      "Izveidojiet abonementu",
      "Dodiet pastāvīgajiem klientiem vairāk iespēju.",
      "Iestatīt abonementu",
    ],
    integrations: [
      "Pievienojiet kanālu",
      "Sagatavojiet vietas, kur cilvēki jūs atklāj.",
      "Skatīt integrācijas",
    ],
    offers: [
      "Sagatavojiet atgriešanās piedāvājumu",
      "Atjaunojiet saikni ar klientiem, kuri vairs neapmeklē.",
      "Skatīt piedāvājumus",
    ],
  },
  later: "Atgriešanās ceļi noderēs, kad būs klientu apmeklējumu vēsture.",
  nextAction: "Jūsu nākamais solis",
  flow: "Klientu plūsma",
  metrics: [
    "Kampaņu skatījumi",
    "Jauni klienti",
    "Atkārtotie klienti",
    "Atgūtie klienti",
  ],
  noMetric: "Nav datu",
  campaigns: "Aktīvās kampaņas",
  noCampaigns: "Vēl nav kampaņu.",
  campaignEmpty:
    "Izveidojiet piedāvājumu vienreiz un sagatavojiet to klientu piesaistes kanāliem.",
  viewCampaign: "Skatīt kampaņu",
  started: "Sākums",
  statuses: {
    DRAFT: "Melnraksts",
    PROCESSING: "Publicē…",
    PUBLISHED: "Publicēts",
    PARTIALLY_PUBLISHED: "Daļēji publicēts",
    FAILED: "Publicēšana neizdevās",
    COMPLETED: "Pabeigta",
    PAUSED: "Apturēts",
  },
  activity: "Klientu aktivitāte",
  noActivity: "Šeit sākas attiecības.",
  activityEmpty:
    "Aktivitāte parādīsies, kad cilvēki pievienosies caur uzņēmuma QR vai klienta pieredzi.",
  viewCustomers: "Skatīt klientus",
  events: {
    joined: "pievienojās uzņēmumam",
    visit: "pabeidza apmeklējumu",
    reward: "ieguva atlīdzību",
    membership: "izmantoja abonementa apmeklējumu",
    redemption: "izmantoja piedāvājumu",
  },
  attention: "Jāpievērš uzmanība",
  noAttention: "Nav stāvokļu, kam jāpievērš uzmanība.",
  attentionReasons: {
    inactive: "Pēdējais apmeklējums pirms {n} dienām",
    expiring: "Abonements beidzas pēc {n} dienām",
    rewardNear: "Līdz atlīdzībai: {n} zīmogs(-i)",
  },
  retention: "Iemesli atgriezties",
  active: "Aktīvi",
  noRetention: "Noturēšanas rīki vēl nav iestatīti.",
  connection: "Klientu savienojums",
  connections: {
    qr: "Uzņēmuma QR",
    profile: "Klienta profils",
    apple: "Apple Wallet",
    google: "Google Wallet",
  },
  integrationHeading: "Kanāli",
  manage: "Pārvaldīt integrācijas",
  configure: "Iestatīt",
  connectionStatuses: {
    ready: "Gatavs",
    connected: "Savienots",
    notConfigured: "Nav iestatīts",
    processing: "Apstrādē",
    failed: "Jāpievērš uzmanība",
  },
  error: "Neizdevās ielādēt pārskatu.",
  errorText:
    "Navigācija joprojām ir pieejama. Mēģiniet vēlreiz, kad savienojums atjaunojas.",
  retry: "Mēģināt vēlreiz",
  loading: "Ielādē darba telpu",
  shellTitle: "Nākamā jūsu plūsmas daļa.",
  shellText:
    "Šī sadaļa ir sagatavota nākamajam MemberFlow posmam. Funkcija vēl nav pieejama.",
  back: "Atpakaļ uz pārskatu",
  noBusiness: "MemberFlow darba telpa",
  planPending: "Plāns nav norādīts",
  noUser: "Jūsu konts",
  account: "Konts",
  businessSettings: "Uzņēmuma iestatījumi",
  billingShell: "Plāna un norēķinu dati tiks saņemti no norēķinu pakalpojuma.",
  profileShell: "Konta profils tiks saņemts no autentifikācijas pakalpojuma.",
  selected: "Pašreizējais uzņēmums",
  availableAfter: "Pēc iestatīšanas",
};
export type DashboardContent = Strings;
export const dashboardContent: Record<Locale, DashboardContent> = {
  en,
  lv,
  ru,
};
