import type { Locale } from "@/content";
const en = {
  title: "Customer Page",
  intro: "The space your customers open after scanning your QR.",
  open: "Open page",
  save: "Save changes",
  saving: "Saving…",
  saved: "Changes saved",
  previewSaved:
    "Preview saved. Public activation needs the MemberFlow service.",
  brand: "Brand",
  business: "Business",
  content: "Content",
  social: "Social links",
  wallet: "Wallet",
  walletReady: "Ready",
  walletNotConfigured: "Not configured",
  invitation: "Printed invitation",
  invitationHint:
    "Used on your business QR sign. Branding is shared with this page.",
  logo: "Logo",
  cover: "Cover image",
  logoHint:
    "Square · recommended 512 × 512 px or larger. JPG, PNG or WebP · up to 6 MB.",
  coverHint:
    "Recommended 1600 × 800 px (2:1). JPG, PNG or WebP · up to 6 MB. Edges may be cropped; keep important details near the centre.",
  accent: "Accent colour",
  upload: "Choose image",
  remove: "Remove",
  uploading: "Preparing image…",
  readingFile: "Reading file",
  sendingFile: "Uploading file",
  processingFile: "Preparing image",
  imageReady: "Image ready",
  uploadFailed: "Couldn’t prepare or upload the image. Try again.",
  uploadError: "Choose a JPG, PNG or WebP image up to 6 MB.",
  temporaryImage:
    "Uploaded images are temporary previews until the media service is connected.",
  name: "Business name",
  category: "Business type",
  city: "City",
  description: "Short description",
  address: "Address",
  hours: "Opening hours",
  phone: "Phone",
  email: "Email",
  website: "Website",
  headline: "Invitation headline",
  message: "Invitation message",
  descriptionPlaceholder:
    "A neighbourhood coffee spot, made for slow mornings.",
  addressPlaceholder: "12 Example Street, Riga",
  hoursPlaceholder: "Mon–Fri 08:00–18:00 · Sat–Sun 09:00–16:00",
  phonePlaceholder: "+371 20 000 000",
  emailPlaceholder: "hello@example.com",
  showOffers: "Show active offers",
  showLoyalty: "Show loyalty",
  showMemberships: "Show memberships",
  showSocial: "Show social links",
  automatic:
    "Offers, loyalty and memberships come from your active business tools. No duplicated content.",
  status: "Page status",
  DRAFT: "Draft",
  ACTIVE: "Active",
  DISABLED: "Disabled",
  activate: "Activate page",
  disable: "Disable page",
  activationUnavailable: "Public activation requires the MemberFlow service.",
  url: "Public page link",
  copy: "Copy link",
  copied: "Link copied",
  copyError: "Couldn't copy the link.",
  qr: "Business QR & A4 sign",
  preview: "Preview as",
  guest: "Guest",
  customer: "Customer",
  previewHint:
    "Customer balances in this editor are illustrative. No customer is created.",
  joinTitle: "Join {business}",
  joinText: "Keep your rewards, offers and visits in one place.",
  join: "Join / Continue",
  noApp: "No app needed",
  greeting: "Hello, {name}.",
  loyalty: "Your rewards",
  loyaltyTeaser: "Earn rewards with every visit.",
  joinRewards: "Join to get started",
  progress: "{current} / {target} stamps",
  nextReward: "Next reward",
  offers: "Offers",
  forYou: "For you",
  viewOffer: "View offer",
  validUntil: "Valid until {date}",
  memberships: "Your memberships",
  visits: "{n} visits remaining",
  walletTitle: "Keep {business} close.",
  walletText:
    "Your customer page stays available in your browser. Wallet is optional.",
  apple: "Add to Apple Wallet",
  google: "Add to Google Wallet",
  walletAdded: "Added to Wallet",
  about: "Visit us",
  contact: "Contact",
  powered: "Connected with MemberFlow",
  discoverMemberships: "Memberships",
  error: "Couldn't load this page.",
  retry: "Try again",
  unavailable: "This customer page is currently unavailable.",
  notFound: "We couldn't find this business.",
  loading: "Loading your customer space…",
  authTitle: "Connect with this business",
  authText: "Enter your phone number to receive a verification code.",
  code: "Verification code",
  sendCode: "Send code",
  verify: "Continue",
  working: "Please wait…",
  authUnavailable:
    "Customer sign-in isn't available yet. Please try again later.",
  authError: "Couldn't continue. Please check your details and try again.",
  codeSent: "Enter the code sent to your phone.",
  logout: "Sign out",
  cancel: "Cancel",
  personalError: "Your customer details couldn't be loaded. Try again.",
  invalid: "Check the highlighted fields.",
  offerUnavailable: "Offer details are not available yet.",
};
type Copy = { [K in keyof typeof en]: string };
export const customerPageContent: Record<Locale, Copy> = {
  en,
  lv: {
    title: "Klienta lapa",
    intro: "Vide, ko klienti atver pēc jūsu QR skenēšanas.",
    open: "Atvērt lapu",
    save: "Saglabāt izmaiņas",
    saving: "Saglabājam…",
    saved: "Izmaiņas saglabātas",
    previewSaved:
      "Priekšskatījums saglabāts. Publiskai aktivizēšanai vajadzīgs MemberFlow serviss.",
    brand: "Zīmols",
    business: "Uzņēmums",
    content: "Saturs",
    social: "Sociālās saites",
    wallet: "Wallet",
    walletReady: "Gatavs",
    walletNotConfigured: "Nav iestatīts",
    invitation: "Drukātais aicinājums",
    invitationHint:
      "Izmanto uzņēmuma QR plakātā. Zīmola dati ir kopīgi ar šo lapu.",
    logo: "Logotips",
    cover: "Vāka attēls",
    logoHint:
      "Kvadrāts · ieteicams 512 × 512 px vai lielāks. JPG, PNG vai WebP · līdz 6 MB.",
    coverHint:
      "Ieteicams 1600 × 800 px (2:1). JPG, PNG vai WebP · līdz 6 MB. Malas var tikt apgrieztas; svarīgās detaļas novietojiet centrā.",
    accent: "Akcenta krāsa",
    upload: "Izvēlēties attēlu",
    remove: "Noņemt",
    uploading: "Sagatavojam attēlu…",
    readingFile: "Lasām failu",
    sendingFile: "Augšupielādējam failu",
    processingFile: "Sagatavojam attēlu",
    imageReady: "Attēls gatavs",
    uploadFailed:
      "Neizdevās sagatavot vai augšupielādēt attēlu. Mēģiniet vēlreiz.",
    uploadError: "Izvēlieties JPG, PNG vai WebP attēlu līdz 6 MB.",
    temporaryImage:
      "Augšupielādētie attēli ir pagaidu priekšskatījumi līdz mediju servisa pieslēgšanai.",
    name: "Uzņēmuma nosaukums",
    category: "Uzņēmuma veids",
    city: "Pilsēta",
    description: "Īss apraksts",
    address: "Adrese",
    hours: "Darba laiks",
    phone: "Tālrunis",
    email: "E-pasts",
    website: "Tīmekļvietne",
    headline: "Aicinājuma virsraksts",
    message: "Aicinājuma teksts",
    descriptionPlaceholder: "Apkaimes kafejnīca nesteidzīgiem rītiem.",
    addressPlaceholder: "Piemēra iela 12, Rīga",
    hoursPlaceholder: "P.–Pk. 08:00–18:00 · S.–Sv. 09:00–16:00",
    phonePlaceholder: "+371 20 000 000",
    emailPlaceholder: "hello@example.com",
    showOffers: "Rādīt aktīvos piedāvājumus",
    showLoyalty: "Rādīt lojalitāti",
    showMemberships: "Rādīt abonementus",
    showSocial: "Rādīt sociālās saites",
    automatic:
      "Piedāvājumus, lojalitāti un abonementus nodrošina aktīvie uzņēmuma rīki. Saturs nav jādublē.",
    status: "Lapas statuss",
    DRAFT: "Melnraksts",
    ACTIVE: "Aktīva",
    DISABLED: "Atspējota",
    activate: "Aktivizēt lapu",
    disable: "Atspējot lapu",
    activationUnavailable:
      "Publiskai aktivizēšanai nepieciešams MemberFlow serviss.",
    url: "Publiskās lapas saite",
    copy: "Kopēt saiti",
    copied: "Saite nokopēta",
    copyError: "Neizdevās kopēt saiti.",
    qr: "Uzņēmuma QR un A4 plakāts",
    preview: "Priekšskatīt kā",
    guest: "Viesis",
    customer: "Klients",
    previewHint:
      "Klienta atlikumi redaktorā ir piemēri. Klients netiek izveidots.",
    joinTitle: "Pievienojieties {business}",
    joinText: "Jūsu balvas, piedāvājumi un apmeklējumi vienuviet.",
    join: "Pievienoties / Turpināt",
    noApp: "Lietotne nav vajadzīga",
    greeting: "Sveiki, {name}.",
    loyalty: "Jūsu balvas",
    loyaltyTeaser: "Saņemiet balvas par katru apmeklējumu.",
    joinRewards: "Pievienojieties, lai sāktu",
    progress: "{current} / {target} zīmogi",
    nextReward: "Nākamā balva",
    offers: "Piedāvājumi",
    forYou: "Jums",
    viewOffer: "Skatīt piedāvājumu",
    validUntil: "Derīgs līdz {date}",
    memberships: "Jūsu abonementi",
    visits: "Atlikuši {n} apmeklējumi",
    walletTitle: "{business} vienmēr tuvumā.",
    walletText: "Klienta lapa ir pieejama pārlūkā. Wallet nav obligāts.",
    apple: "Pievienot Apple Wallet",
    google: "Pievienot Google Wallet",
    walletAdded: "Pievienots Wallet",
    about: "Apmeklējiet mūs",
    contact: "Kontakti",
    powered: "Saikni veido MemberFlow",
    discoverMemberships: "Abonementi",
    error: "Neizdevās ielādēt lapu.",
    retry: "Mēģināt vēlreiz",
    unavailable: "Šī klienta lapa pašlaik nav pieejama.",
    notFound: "Neizdevās atrast šo uzņēmumu.",
    loading: "Ielādējam klientu vidi…",
    authTitle: "Pievienojieties uzņēmumam",
    authText: "Ievadiet tālruņa numuru, lai saņemtu verifikācijas kodu.",
    code: "Verifikācijas kods",
    sendCode: "Nosūtīt kodu",
    verify: "Turpināt",
    working: "Lūdzu, uzgaidiet…",
    authUnavailable: "Klientu pieslēgšanās vēl nav pieejama. Mēģiniet vēlāk.",
    authError: "Neizdevās turpināt. Pārbaudiet datus un mēģiniet vēlreiz.",
    codeSent: "Ievadiet uz tālruni nosūtīto kodu.",
    logout: "Izrakstīties",
    cancel: "Atcelt",
    personalError: "Neizdevās ielādēt klienta datus. Mēģiniet vēlreiz.",
    invalid: "Pārbaudiet atzīmētos laukus.",
    offerUnavailable: "Piedāvājuma informācija vēl nav pieejama.",
  },
  ru: {
    title: "Клиентская страница",
    intro:
      "Пространство, которое открывают ваши клиенты после сканирования QR.",
    open: "Открыть страницу",
    save: "Сохранить изменения",
    saving: "Сохраняем…",
    saved: "Изменения сохранены",
    previewSaved:
      "Предпросмотр сохранён. Для публичной активации нужен сервис MemberFlow.",
    brand: "Бренд",
    business: "Бизнес",
    content: "Содержимое",
    social: "Социальные ссылки",
    wallet: "Wallet",
    walletReady: "Готово",
    walletNotConfigured: "Не настроено",
    invitation: "Приглашение на печатном листе",
    invitationHint:
      "Используется на листе с QR бизнеса. Оформление общее с клиентской страницей.",
    logo: "Логотип",
    cover: "Обложка",
    logoHint:
      "Квадрат · рекомендуем от 512 × 512 px. JPG, PNG или WebP · до 6 МБ.",
    coverHint:
      "Рекомендуем 1600 × 800 px (2:1). JPG, PNG или WebP · до 6 МБ. Края могут обрезаться — важные детали держите ближе к центру.",
    accent: "Цвет акцента",
    upload: "Выбрать изображение",
    remove: "Удалить",
    uploading: "Готовим изображение…",
    readingFile: "Читаем файл",
    sendingFile: "Загружаем файл",
    processingFile: "Готовим изображение",
    imageReady: "Изображение готово",
    uploadFailed:
      "Не удалось подготовить или загрузить изображение. Попробуйте снова.",
    uploadError: "Выберите JPG, PNG или WebP до 6 МБ.",
    temporaryImage:
      "Загруженные изображения — временный предпросмотр до подключения медиасервиса.",
    name: "Название бизнеса",
    category: "Тип бизнеса",
    city: "Город",
    description: "Короткое описание",
    address: "Адрес",
    hours: "Часы работы",
    phone: "Телефон",
    email: "Email",
    website: "Сайт",
    headline: "Заголовок приглашения",
    message: "Текст приглашения",
    descriptionPlaceholder:
      "Кофейня по соседству для неспешных утренних встреч.",
    addressPlaceholder: "Улица Примерная, 12, Рига",
    hoursPlaceholder: "Пн–Пт 08:00–18:00 · Сб–Вс 09:00–16:00",
    phonePlaceholder: "+371 20 000 000",
    emailPlaceholder: "hello@example.com",
    showOffers: "Показывать активные предложения",
    showLoyalty: "Показывать лояльность",
    showMemberships: "Показывать абонементы",
    showSocial: "Показывать социальные ссылки",
    automatic:
      "Предложения, лояльность и абонементы поступают из активных инструментов бизнеса. Контент не нужно дублировать.",
    status: "Статус страницы",
    DRAFT: "Черновик",
    ACTIVE: "Активна",
    DISABLED: "Отключена",
    activate: "Активировать страницу",
    disable: "Отключить страницу",
    activationUnavailable: "Для публичной активации нужен сервис MemberFlow.",
    url: "Публичная ссылка",
    copy: "Копировать ссылку",
    copied: "Ссылка скопирована",
    copyError: "Не удалось скопировать ссылку.",
    qr: "QR бизнеса и лист A4",
    preview: "Посмотреть как",
    guest: "Гость",
    customer: "Клиент",
    previewHint:
      "Данные клиента в редакторе — пример. Реальный клиент не создаётся.",
    joinTitle: "Присоединитесь к {business}",
    joinText: "Ваши награды, предложения и визиты в одном месте.",
    join: "Присоединиться / Продолжить",
    noApp: "Без установки приложения",
    greeting: "Здравствуйте, {name}.",
    loyalty: "Ваши награды",
    loyaltyTeaser: "Получайте награды за каждый визит.",
    joinRewards: "Присоединиться и начать",
    progress: "{current} / {target} штампов",
    nextReward: "Следующая награда",
    offers: "Предложения",
    forYou: "Для вас",
    viewOffer: "Посмотреть предложение",
    validUntil: "Действует до {date}",
    memberships: "Ваши абонементы",
    visits: "Осталось посещений: {n}",
    walletTitle: "{business} всегда рядом.",
    walletText: "Клиентская страница доступна в браузере. Wallet — по желанию.",
    apple: "Добавить в Apple Wallet",
    google: "Добавить в Google Wallet",
    walletAdded: "Добавлено в Wallet",
    about: "Загляните к нам",
    contact: "Контакты",
    powered: "На связи через MemberFlow",
    discoverMemberships: "Абонементы",
    error: "Не удалось загрузить страницу.",
    retry: "Повторить",
    unavailable: "Эта клиентская страница сейчас недоступна.",
    notFound: "Не удалось найти этот бизнес.",
    loading: "Загружаем клиентское пространство…",
    authTitle: "Подключитесь к бизнесу",
    authText: "Введите номер телефона, чтобы получить код подтверждения.",
    code: "Код подтверждения",
    sendCode: "Отправить код",
    verify: "Продолжить",
    working: "Подождите…",
    authUnavailable: "Вход для клиентов пока недоступен. Попробуйте позже.",
    authError: "Не удалось продолжить. Проверьте данные и попробуйте снова.",
    codeSent: "Введите код, отправленный на телефон.",
    logout: "Выйти",
    cancel: "Отмена",
    personalError: "Не удалось загрузить ваши данные. Попробуйте снова.",
    invalid: "Проверьте отмеченные поля.",
    offerUnavailable: "Подробности предложения пока недоступны.",
  },
};

export const customerCategories: Record<Locale, Record<string, string>> = {
  en: {
    cafe: "Café & Restaurant",
    beauty: "Beauty & Wellness",
    fitness: "Fitness & Gym",
    retail: "Retail",
    services: "Services",
    other: "Other",
  },
  lv: {
    cafe: "Kafejnīca un restorāns",
    beauty: "Skaistums un labsajūta",
    fitness: "Sports un fitness",
    retail: "Mazumtirdzniecība",
    services: "Pakalpojumi",
    other: "Cits",
  },
  ru: {
    cafe: "Кафе и ресторан",
    beauty: "Красота и здоровье",
    fitness: "Фитнес и спорт",
    retail: "Розничная торговля",
    services: "Услуги",
    other: "Другое",
  },
};
