import type { AuthContent } from "./types";
export const en = {
  welcome: "Welcome back.",
  intro: "Log in to your MemberFlow account.",
  email: "Email",
  password: "Password",
  show: "Show password",
  hide: "Hide password",
  forgot: "Forgot password?",
  login: "Log in",
  loading: "Logging in…",
  newUser: "New to MemberFlow?",
  start: "Start free",
  backHome: "Back to MemberFlow",
  access: "01 — MEMBERFLOW ACCESS",
  visual: "Pick up where you left off.",
  resetTitle: "Forgot your password?",
  resetIntro: "Enter the email associated with your MemberFlow account.",
  sendReset: "Send reset link",
  sending: "Sending…",
  backLogin: "Back to login",
  invalidCredentials: "Incorrect email or password.",
  tooMany: "Too many attempts. Please try again later.",
  network: "Unable to connect. Please try again.",
  expired: "Your session has expired. Please log in again.",
  unavailable:
    "Sign-in and password recovery will be available when the account service launches. No account was accessed and no email was sent.",
  requiredEmail: "Enter your email.",
  invalidEmail: "Enter a valid email address.",
  requiredPassword: "Enter your password.",
  fieldInvalid: "Please check this field.",
  resetSent:
    "If an account matches this email, you’ll receive password reset instructions.",
  already: "Already have an account?",
  language: "Language",
  resetAccess: "02 — ACCOUNT RECOVERY",
} satisfies AuthContent;
