import type { AuthContent } from "./types";
export const lv = {
  welcome: "Prieks atkal redzēt.",
  intro: "Ieej savā MemberFlow kontā.",
  email: "E-pasts",
  password: "Parole",
  show: "Rādīt paroli",
  hide: "Slēpt paroli",
  forgot: "Aizmirsi paroli?",
  login: "Ieiet",
  loading: "Pieslēdzamies…",
  newUser: "Pirmo reizi MemberFlow?",
  start: "Sākt bez maksas",
  backHome: "Atpakaļ uz MemberFlow",
  access: "01 — MEMBERFLOW PIEKĻUVE",
  visual: "Turpini no vietas, kur apstājies.",
  resetTitle: "Aizmirsi paroli?",
  resetIntro: "Ievadi ar savu MemberFlow kontu saistīto e-pastu.",
  sendReset: "Nosūtīt atjaunošanas saiti",
  sending: "Nosūtām…",
  backLogin: "Atpakaļ uz ieeju",
  invalidCredentials: "Nepareizs e-pasts vai parole.",
  tooMany: "Pārāk daudz mēģinājumu. Lūdzu, mēģini vēlāk.",
  network: "Neizdevās savienoties. Mēģini vēlreiz.",
  expired: "Sesija ir beigusies. Lūdzu, ieej vēlreiz.",
  unavailable:
    "Ieeja un paroles atjaunošana būs pieejama pēc kontu servisa palaišanas. Ieeja nav veikta un e-pasts nav nosūtīts.",
  requiredEmail: "Ievadi savu e-pastu.",
  invalidEmail: "Ievadi derīgu e-pasta adresi.",
  requiredPassword: "Ievadi savu paroli.",
  fieldInvalid: "Pārbaudi šo lauku.",
  resetSent:
    "Ja šim e-pastam atbilst konts, saņemsi paroles atjaunošanas norādes.",
  already: "Jau ir konts?",
  language: "Valoda",
  resetAccess: "02 — PIEKĻUVES ATJAUNOŠANA",
} satisfies AuthContent;
