import type { AuthContent } from "./types";
export const ru = {
  welcome: "С возвращением.",
  intro: "Войдите в свой аккаунт MemberFlow.",
  email: "Email",
  password: "Пароль",
  show: "Показать пароль",
  hide: "Скрыть пароль",
  forgot: "Забыли пароль?",
  login: "Войти",
  loading: "Входим…",
  newUser: "Впервые в MemberFlow?",
  start: "Начать бесплатно",
  backHome: "Вернуться в MemberFlow",
  access: "01 — ВХОД В MEMBERFLOW",
  visual: "Продолжите с того, где остановились.",
  resetTitle: "Забыли пароль?",
  resetIntro: "Введите email вашего аккаунта MemberFlow.",
  sendReset: "Отправить ссылку",
  sending: "Отправляем…",
  backLogin: "Вернуться ко входу",
  invalidCredentials: "Неверный email или пароль.",
  tooMany: "Слишком много попыток. Попробуйте позже.",
  network: "Не удалось подключиться. Попробуйте ещё раз.",
  expired: "Сессия истекла. Войдите снова.",
  unavailable:
    "Вход и восстановление пароля станут доступны после запуска сервиса аккаунтов. Вход не выполнен, письмо не отправлено.",
  requiredEmail: "Введите email.",
  invalidEmail: "Введите корректный email.",
  requiredPassword: "Введите пароль.",
  fieldInvalid: "Проверьте это поле.",
  resetSent:
    "Если аккаунт с таким email существует, вы получите инструкции для восстановления пароля.",
  already: "Уже есть аккаунт?",
  language: "Язык",
  resetAccess: "02 — ВОССТАНОВЛЕНИЕ ДОСТУПА",
} satisfies AuthContent;
