const en = {
  title: "Customers",
  intro: "Visits, relationships and customer activity in one place.",
  add: "Add customer",
  edit: "Edit details",
  profile: "Open profile",
  period: "Period",
  days: "Last {n} days",
  all: "All customers",
  returning: "Returning",
  inactive: "Inactive",
  search: "Search name, email or phone",
  total: "Customers",
  newCustomers: "New customers",
  visits: "Visits",
  returningCustomers: "Returning customers",
  inactiveCustomers: "Inactive customers",
  sales: "Net sales",
  salesMissing:
    "Sales data is not connected. Visits and stamps do not indicate spending.",
  activity: "Customer activity",
  trend: "Visits and new customers",
  chartEmpty: "Activity will appear after customers start visiting.",
  directory: "Customer directory",
  lastVisit: "Last visit",
  visitCount: "Total visits",
  spending: "Total spending",
  never: "No visits yet",
  unknown: "Not available",
  noCustomers: "No customers yet",
  empty:
    "Customers will appear when they connect through your QR or customer page. You can also add a customer.",
  noResults: "No matching customers",
  connection: "Customer connection",
  connect: "Set up business QR",
  load: "Loading customers…",
  error: "Couldn't load customer data.",
  retry: "Try again",
  back: "Back to customers",
  joined: "Customer since",
  email: "Email",
  phone: "Phone",
  remainingVisits: "Visits remaining",
  validUntil: "Valid until",
  contact: "Contact details",
  loyalty: "Loyalty",
  nextReward: "Next reward",
  membership: "Memberships",
  noMembership: "No memberships",
  noLoyalty: "No loyalty account",
  rewards: "Rewards earned",
  offers: "Offers redeemed",
  history: "Activity history",
  noHistory: "No activity yet",
  purchases: "Purchases",
  noPurchases: "No purchases recorded",
  notes: "Notes",
  actor: "Recorded by {name}",
  previous: "Previous",
  next: "Next",
  page: "Page {page}",
  results: "{n} customers",
  states: {
    NEW: "New",
    RETURNING: "Returning",
    INACTIVE: "Inactive",
    UNKNOWN: "No history",
  },
  membershipStates: { ACTIVE: "Active", EXPIRED: "Expired", PAUSED: "Paused" },
  purchaseStates: {
    PAID: "Paid",
    REFUNDED: "Refunded",
    PARTIALLY_REFUNDED: "Partially refunded",
  },
};
export const customersContent = {
  en,
  ru: {
    title: "Клиенты",
    intro: "Визиты, отношения с клиентами и их активность в одном месте.",
    add: "Добавить клиента",
    edit: "Редактировать данные",
    profile: "Открыть профиль",
    period: "Период",
    days: "Последние {n} дней",
    all: "Все клиенты",
    returning: "Возвращающиеся",
    inactive: "Неактивные",
    search: "Поиск по имени, email или телефону",
    total: "Клиенты",
    newCustomers: "Новые клиенты",
    visits: "Визиты",
    returningCustomers: "Вернувшиеся клиенты",
    inactiveCustomers: "Неактивные клиенты",
    sales: "Продажи с учётом возвратов",
    salesMissing:
      "Данные о продажах не подключены. Визиты и штампы не определяют сумму покупок.",
    activity: "Активность клиентов",
    trend: "Визиты и новые клиенты",
    chartEmpty: "Активность появится, когда клиенты начнут посещать бизнес.",
    directory: "Список клиентов",
    lastVisit: "Последний визит",
    visitCount: "Всего визитов",
    spending: "Всего потрачено",
    never: "Визитов пока нет",
    unknown: "Нет данных",
    noCustomers: "Клиентов пока нет",
    empty:
      "Клиенты появятся после подключения через QR или клиентскую страницу. Также можно добавить клиента вручную.",
    noResults: "Клиенты не найдены",
    connection: "Подключение клиентов",
    connect: "Настроить QR бизнеса",
    load: "Загрузка клиентов…",
    error: "Не удалось загрузить данные клиентов.",
    retry: "Повторить",
    back: "Назад к клиентам",
    joined: "Клиент с",
    email: "Email",
    phone: "Телефон",
    remainingVisits: "Осталось посещений",
    validUntil: "Действует до",
    contact: "Контактные данные",
    loyalty: "Лояльность",
    nextReward: "Следующая награда",
    membership: "Абонементы",
    noMembership: "Абонементов нет",
    noLoyalty: "Программа лояльности не подключена",
    rewards: "Получено наград",
    offers: "Использовано предложений",
    history: "История активности",
    noHistory: "Активности пока нет",
    purchases: "Покупки",
    noPurchases: "Покупок пока нет",
    notes: "Заметки",
    actor: "Записал: {name}",
    previous: "Назад",
    next: "Далее",
    page: "Страница {page}",
    results: "Клиентов: {n}",
    states: {
      NEW: "Новый",
      RETURNING: "Возвращается",
      INACTIVE: "Неактивен",
      UNKNOWN: "Без истории",
    },
    membershipStates: {
      ACTIVE: "Активен",
      EXPIRED: "Истёк",
      PAUSED: "Приостановлен",
    },
    purchaseStates: {
      PAID: "Оплачено",
      REFUNDED: "Возврат",
      PARTIALLY_REFUNDED: "Частичный возврат",
    },
  },
  lv: {
    title: "Klienti",
    intro: "Apmeklējumi, attiecības un klientu aktivitāte vienuviet.",
    add: "Pievienot klientu",
    edit: "Rediģēt datus",
    profile: "Atvērt profilu",
    period: "Periods",
    days: "Pēdējās {n} dienas",
    all: "Visi klienti",
    returning: "Atkārtotie klienti",
    inactive: "Neaktīvie",
    search: "Meklēt pēc vārda, e-pasta vai tālruņa",
    total: "Klienti",
    newCustomers: "Jaunie klienti",
    visits: "Apmeklējumi",
    returningCustomers: "Atkārtotie klienti",
    inactiveCustomers: "Neaktīvie klienti",
    sales: "Neto pārdošana",
    salesMissing:
      "Pārdošanas dati nav pievienoti. Apmeklējumi un zīmogi nenorāda pirkumu summu.",
    activity: "Klientu aktivitāte",
    trend: "Apmeklējumi un jaunie klienti",
    chartEmpty: "Aktivitāte parādīsies, kad klienti sāks apmeklēt uzņēmumu.",
    directory: "Klientu saraksts",
    lastVisit: "Pēdējais apmeklējums",
    visitCount: "Apmeklējumi kopā",
    spending: "Iztērēts kopā",
    never: "Vēl nav apmeklējumu",
    unknown: "Nav datu",
    noCustomers: "Vēl nav klientu",
    empty:
      "Klienti parādīsies pēc pievienošanās ar QR vai klienta lapu. Klientu var pievienot arī manuāli.",
    noResults: "Klienti nav atrasti",
    connection: "Klientu piesaiste",
    connect: "Iestatīt uzņēmuma QR",
    load: "Ielādē klientus…",
    error: "Neizdevās ielādēt klientu datus.",
    retry: "Mēģināt vēlreiz",
    back: "Atpakaļ pie klientiem",
    joined: "Klients kopš",
    email: "E-pasts",
    phone: "Tālrunis",
    remainingVisits: "Atlikušie apmeklējumi",
    validUntil: "Derīgs līdz",
    contact: "Kontaktinformācija",
    loyalty: "Lojalitāte",
    nextReward: "Nākamā atlīdzība",
    membership: "Abonementi",
    noMembership: "Nav abonementu",
    noLoyalty: "Nav lojalitātes konta",
    rewards: "Saņemtās atlīdzības",
    offers: "Izmantotie piedāvājumi",
    history: "Aktivitātes vēsture",
    noHistory: "Vēl nav aktivitātes",
    purchases: "Pirkumi",
    noPurchases: "Nav reģistrētu pirkumu",
    notes: "Piezīmes",
    actor: "Reģistrēja: {name}",
    previous: "Iepriekšējā",
    next: "Nākamā",
    page: "Lapa {page}",
    results: "{n} klienti",
    states: {
      NEW: "Jauns",
      RETURNING: "Atgriežas",
      INACTIVE: "Neaktīvs",
      UNKNOWN: "Bez vēstures",
    },
    membershipStates: {
      ACTIVE: "Aktīvs",
      EXPIRED: "Beidzies",
      PAUSED: "Apturēts",
    },
    purchaseStates: {
      PAID: "Apmaksāts",
      REFUNDED: "Atmaksāts",
      PARTIALLY_REFUNDED: "Daļēji atmaksāts",
    },
  },
};
