import type { Locale } from "@/content";
const en = {
  title: "Customer connection",
  intro:
    "A simple invitation at your counter. One scan connects a customer to your business.",
  back: "Customers",
  poster: "Your business QR",
  posterIntro:
    "This QR opens your Customer Page. Print an A4 sign for your counter, entrance or tables.",
  headline: "Make yourself a regular.",
  description: "Scan to join our customer space and stay connected.",
  scan: "Scan with your phone camera",
  powered: "Connected by MemberFlow",
  format: "A4 · 210 × 297 mm",
  print: "Print / Save PDF",
  download: "Download QR · SVG",
  copy: "Copy link",
  copied: "Link copied",
  copyError: "Couldn't copy the link. You can select it below.",
  settings: "Make it yours",
  headingLabel: "Invitation headline",
  descriptionLabel: "Short message",
  showLogo: "Show business logo",
  showCity: "Show city",
  link: "Customer page link",
  status: "Customer access",
  ready: "Ready to share",
  pending: "Public link is not activated yet",
  draft: "Print layout preview",
  sample: "SAMPLE · Customer registration is not connected",
  note: "Your permanent customer link will be supplied by the MemberFlow service. This sample QR opens a preview; it does not register customers.",
  how: "Place it where a visit begins",
  tip: "Print at actual size on A4. Keep the QR clear and test the final public link before placing the sign in your business.",
  error: "Couldn't load your customer connection.",
  retry: "Try again",
  qrError: "Couldn't prepare the QR. Try again.",
  loading: "Preparing your sign…",
  customerSpace: "Your customer space",
  unavailable:
    "Customer registration will be available when this business connects its customer service.",
  join: "Join this business",
  unavailableTitle: "This customer page is not available yet.",
};
type Copy = { [K in keyof typeof en]: string };
export const connectionContent: Record<Locale, Copy> = {
  en,
  lv: {
    title: "Klientu pievienošanās",
    intro:
      "Vienkāršs aicinājums pie letes. Viens skenējums savieno klientu ar jūsu uzņēmumu.",
    back: "Klienti",
    poster: "Jūsu uzņēmuma QR",
    posterIntro:
      "Šis QR atver jūsu klienta lapu. Izdrukājiet A4 plakātu letei, ieejai vai galdiņiem.",
    headline: "Kļūstiet par pastāvīgu klientu.",
    description:
      "Skenējiet, lai pievienotos mūsu klientu videi un uzturētu saikni.",
    scan: "Skenējiet ar tālruņa kameru",
    powered: "Saikni veido MemberFlow",
    format: "A4 · 210 × 297 mm",
    print: "Drukāt / Saglabāt PDF",
    download: "Lejupielādēt QR · SVG",
    copy: "Kopēt saiti",
    copied: "Saite nokopēta",
    copyError: "Neizdevās nokopēt saiti. Atlasiet to zemāk.",
    settings: "Pielāgojiet savam uzņēmumam",
    headingLabel: "Aicinājuma virsraksts",
    descriptionLabel: "Īss ziņojums",
    showLogo: "Rādīt uzņēmuma logotipu",
    showCity: "Rādīt pilsētu",
    link: "Klientu lapas saite",
    status: "Klientu piekļuve",
    ready: "Gatavs kopīgošanai",
    pending: "Publiskā saite vēl nav aktivizēta",
    draft: "Drukas maketa priekšskatījums",
    sample: "PARAUGS · Klientu reģistrācija nav pieslēgta",
    note: "Pastāvīgo klientu saiti nodrošinās MemberFlow serviss. Šis parauga QR atver priekšskatījumu un nereģistrē klientus.",
    how: "Novietojiet tur, kur sākas apmeklējums",
    tip: "Drukājiet uz A4 faktiskajā izmērā. Saglabājiet QR skaidri salasāmu un pārbaudiet galīgo publisko saiti pirms plakāta izvietošanas.",
    error: "Neizdevās ielādēt klientu pievienošanos.",
    retry: "Mēģināt vēlreiz",
    qrError: "Neizdevās sagatavot QR. Mēģiniet vēlreiz.",
    loading: "Sagatavojam plakātu…",
    customerSpace: "Jūsu klientu vide",
    unavailable:
      "Klientu reģistrācija būs pieejama, kad uzņēmums pieslēgs klientu servisu.",
    join: "Pievienoties uzņēmumam",
    unavailableTitle: "Šī klientu lapa vēl nav pieejama.",
  },
  ru: {
    title: "Подключение клиентов",
    intro:
      "Приглашение у вашей стойки. Один скан соединяет клиента с вашим бизнесом.",
    back: "Клиенты",
    poster: "QR вашего бизнеса",
    posterIntro:
      "Этот код открывает вашу клиентскую страницу. Распечатайте лист A4 для стойки, входа или столиков.",
    headline: "Станьте нашим постоянным гостем.",
    description:
      "Отсканируйте код, чтобы присоединиться к нашему клиентскому пространству и оставаться на связи.",
    scan: "Наведите камеру телефона",
    powered: "На связи через MemberFlow",
    format: "A4 · 210 × 297 мм",
    print: "Печать / Сохранить PDF",
    download: "Скачать QR · SVG",
    copy: "Копировать ссылку",
    copied: "Ссылка скопирована",
    copyError: "Не удалось скопировать ссылку. Можно выделить её ниже.",
    settings: "Оформление листа",
    headingLabel: "Заголовок приглашения",
    descriptionLabel: "Короткое сообщение",
    showLogo: "Показывать логотип бизнеса",
    showCity: "Показывать город",
    link: "Ссылка на страницу для клиентов",
    status: "Доступ для клиентов",
    ready: "Можно размещать",
    pending: "Публичная ссылка ещё не активирована",
    draft: "Предпросмотр печатного макета",
    sample: "ОБРАЗЕЦ · Регистрация клиентов не подключена",
    note: "Постоянную ссылку для клиентов предоставит сервис MemberFlow. QR в образце открывает предпросмотр и не регистрирует клиентов.",
    how: "Разместите там, где начинается визит",
    tip: "Печатайте на A4 в исходном размере. Оставьте QR хорошо читаемым и проверьте готовую публичную ссылку перед размещением в бизнесе.",
    error: "Не удалось загрузить подключение клиентов.",
    retry: "Повторить",
    qrError: "Не удалось подготовить QR. Попробуйте снова.",
    loading: "Готовим ваш лист…",
    customerSpace: "Ваше клиентское пространство",
    unavailable:
      "Регистрация клиентов появится, когда бизнес подключит клиентский сервис.",
    join: "Присоединиться к бизнесу",
    unavailableTitle: "Эта клиентская страница пока недоступна.",
  },
};
