import type { OnboardingContent } from "./types";
export const en = {
  priceFrom: "from",
  perMonth: "/ month",
  perYear: "/ year",
  customPrice: "Custom",
  planCopy: {"starter": {"description": "Core tools for connecting with your customers.", "features": ["Branded customer portal", "Loyalty and rewards", "QR onboarding", "Up to 300 active customers", "Basic analytics"]}, "growth": {"description": "More ways to build repeat customer relationships.", "features": ["Personal offers", "Ready automations", "Visit packages", "Customer export", "Up to 1,500 active customers"]}, "business": {"description": "A flexible plan for businesses with broader needs.", "features": ["Multiple locations", "Advanced analytics", "Roles and permissions", "Subscriptions and renewals", "Priority support"]}},
  placeholders: {
    description: "A neighbourhood café in Riga serving specialty coffee and fresh pastries.",
    website: "https://yourcoffee.example",
    instagram: "@yourcoffee",
  },
  setupDuration: "Setup takes about 5–10 minutes",
  steps: ["Account", "Business", "Goals", "Setup", "Plan"],
  headlines: [
    "Create your account.",
    "Tell us about your business.",
    "What do you want to grow?",
    "Make MemberFlow yours.",
    "Choose how you want to grow.",
  ],
  support: [
    "First, let’s set up your personal MemberFlow account.",
    "A few details about the business you manage.",
    "Choose what matters now. You can change this later.",
    "Add a little character. All of these details are optional.",
    "Start with what fits your business today. You can change your plan later.",
  ],
  continue: "Continue",
  back: "Back",
  skip: "Skip for now",
  previewLabel: "DEVELOPMENT PREVIEW",
  previewNotice:
    "Explore the setup journey. No account, business or subscription is created. Your entries stay in this page and are cleared on reload.",
  firstName: "First name",
  email: "Email",
  password: "Password",
  passwordHint: "Preview only: use a sample password, not a real credential.",
  terms: "I accept the Terms",
  privacy: "I accept the Privacy policy",
  businessName: "Business name",
  otherBusinessType: "Describe your business type",
  businessType: "Business type",
  types: [
    "Café & Restaurant",
    "Beauty & Wellness",
    "Fitness & Gym",
    "Retail",
    "Services",
    "Other",
  ],
  chooseCountry: "Choose a country",
  country: "Country",
  city: "City",
  goals: [
    "Reach new customers",
    "Create & distribute campaigns",
    "Build customer relationships",
    "Loyalty & rewards",
    "Memberships & packages",
    "Understand returning customers",
    "Bring inactive customers back",
  ],
  logo: "Business logo (optional)",
  accent: "Brand colour (optional)",
  incompleteStep: "Required details missing",
  planLocked: "Choose your plan after completing the required account, business and goals details. Setup is optional.",
  logoBorder: "Logo border",
  description: "Short description (optional)",
  website: "Website (optional)",
  instagram: "Instagram (optional)",
  monthly: "Monthly",
  yearlyDiscount: "Save {percent}%",
  yearly: "Yearly",
  pricePending: "Price to be confirmed",
  planDescription:
    "Development plan placeholder. Final name, features and limits will be defined before launch.",
  catalogNotice: "Plan features describe the intended product. Billing and activation will be handled by Symfony.",
  select: "Select",
  selected: "Selected",
  businessContext: "YOUR BUSINESS",
  goalsContext: "YOUR GOALS",
  recommended: "Recommended",
  checkoutTitle: "Your plan is selected.",
  checkoutDescription:
    "Subscription and trial activation need the Symfony billing integration. No payment is taken and workspace access is not activated.",
  workspacePreviewDescription:
    "You can now explore your MemberFlow workspace. No payment is taken; subscription and trial activation will be connected separately.",
  editPlan: "Change plan",
  readyFlow: ["Create", "Reach", "Connect", "Return"],
  ready: "Your MemberFlow is ready.",
  openWorkspace: "Open MemberFlow",
  previewTabs: ["Loyalty", "Membership", "Offers"],
  logoHint: "PNG, JPEG or WebP, up to 5 MB. Preview only.",
  goalHint: "Select at least one goal. All goals are available here.",
  planHint: "Select a plan to continue.",
} satisfies OnboardingContent;
