import type { OnboardingContent } from "./types";
export const lv = {
  priceFrom: "no",
  perMonth: "/ mēnesī",
  perYear: "/ gadā",
  customPrice: "Individuāli",
  planCopy: {"starter": {"description": "Pamata rīki saiknes veidošanai ar klientiem.", "features": ["Zīmolam pielāgots klientu portāls", "Lojalitāte un atlīdzības", "Pievienošanās ar QR", "Līdz 300 aktīviem klientiem", "Pamata analītika"]}, "growth": {"description": "Vairāk iespēju veidot attiecības ar pastāvīgajiem klientiem.", "features": ["Personīgi piedāvājumi", "Gatavas automatizācijas", "Apmeklējumu paketes", "Klientu eksports", "Līdz 1 500 aktīviem klientiem"]}, "business": {"description": "Elastīgs plāns uzņēmumiem ar plašākām vajadzībām.", "features": ["Vairākas atrašanās vietas", "Paplašināta analītika", "Lomas un piekļuves tiesības", "Abonementi un atjaunošana", "Prioritārs atbalsts"]}},
  placeholders: {
    description: "Mājīga kafejnīca Rīgā ar īpaši atlasītu kafiju un svaigiem konditorejas izstrādājumiem.",
    website: "https://yourcoffee.example",
    instagram: "@yourcoffee",
  },
  setupDuration: "Iestatīšana aizņems aptuveni 5–10 minūtes",
  steps: ["Konts", "Bizness", "Mērķi", "Noformējums", "Plāns"],
  headlines: [
    "Izveido savu kontu.",
    "Pastāsti par savu biznesu.",
    "Ko vēlies attīstīt?",
    "Pielāgo MemberFlow sev.",
    "Izvēlies savu izaugsmes ceļu.",
  ],
  support: [
    "Vispirms izveidosim tavu personīgo MemberFlow kontu.",
    "Dažas detaļas par biznesu, kuru pārvaldi.",
    "Izvēlies svarīgāko šobrīd. Vēlāk to varēsi mainīt.",
    "Piešķir raksturu. Visi šie lauki ir neobligāti.",
    "Sāc ar piemērotāko plānu. Vēlāk to varēsi mainīt.",
  ],
  continue: "Turpināt",
  back: "Atpakaļ",
  skip: "Pagaidām izlaist",
  previewLabel: "REĢISTRĀCIJAS PRIEKŠSKATĪJUMS",
  previewNotice:
    "Iepazīsti iestatīšanas ceļu. Konts, bizness un abonements netiek izveidoti. Dati paliek šajā lapā un pazūd pēc pārlādes.",
  firstName: "Vārds",
  email: "E-pasts",
  password: "Parole",
  passwordHint: "Priekšskatījumā izmanto paroles piemēru, nevis īstu paroli.",
  terms: "Piekrītu noteikumiem",
  privacy: "Piekrītu privātuma politikai",
  businessName: "Biznesa nosaukums",
  otherBusinessType: "Norādi savu biznesa veidu",
  businessType: "Biznesa veids",
  types: [
    "Kafejnīcas un restorāni",
    "Skaistums un labsajūta",
    "Fitness un sporta zāles",
    "Mazumtirdzniecība",
    "Pakalpojumi",
    "Cits",
  ],
  chooseCountry: "Izvēlies valsti",
  country: "Valsts",
  city: "Pilsēta",
  goals: [
    "Piesaistīt jaunus klientus",
    "Veidot un izplatīt kampaņas",
    "Attīstīt attiecības ar klientiem",
    "Lojalitāte un atlīdzības",
    "Abonementi un paketes",
    "Saprast, kuri klienti atgriežas",
    "Atgriezt neaktīvos klientus",
  ],
  logo: "Logotips (neobligāti)",
  accent: "Zīmola krāsa (neobligāti)",
  incompleteStep: "Nav aizpildīta obligātā informācija",
  planLocked: "Plānu varēs izvēlēties pēc konta, uzņēmuma un mērķu obligātās informācijas aizpildīšanas. Noformējums nav obligāts.",
  logoBorder: "Logotipa apmale",
  description: "Īss apraksts (neobligāti)",
  website: "Mājaslapa (neobligāti)",
  instagram: "Instagram (neobligāti)",
  monthly: "Mēnesis",
  yearlyDiscount: "Ietaupi {percent}%",
  yearly: "Gads",
  pricePending: "Cena vēl tiks noteikta",
  planDescription:
    "Izstrādes plāna piemērs. Nosaukums, iespējas un limiti tiks noteikti pirms palaišanas.",
  catalogNotice: "Plānu iespējas apraksta iecerēto produktu. Maksājumus un aktivizēšanu nodrošinās Symfony.",
  select: "Izvēlēties",
  selected: "Izvēlēts",
  businessContext: "TAVS BIZNESS",
  goalsContext: "TAVI MĒRĶI",
  recommended: "Ieteicams",
  checkoutTitle: "Plāns ir izvēlēts.",
  checkoutDescription:
    "Abonementa vai izmēģinājuma aktivizācijai vajadzīga Symfony maksājumu integrācija. Šeit priekšskatījums beidzas. Maksājums netiek veikts un darba vide netiek aktivizēta.",
  workspacePreviewDescription:
    "Tagad varat atvērt MemberFlow darba telpu. Maksājums netiek veikts; abonementa un izmēģinājuma aktivizācija tiks pievienota atsevišķi.",
  editPlan: "Mainīt plānu",
  readyFlow: ["Radīt", "Sasniegt", "Savienot", "Atgriezt"],
  ready: "Tavs MemberFlow ir gatavs.",
  openWorkspace: "Atvērt MemberFlow",
  previewTabs: ["Lojalitāte", "Abonements", "Piedāvājumi"],
  logoHint: "PNG, JPEG vai WebP, līdz 5 MB. Tikai priekšskatījumam.",
  goalHint: "Izvēlies vismaz vienu mērķi. Šeit pieejami visi mērķi.",
  planHint: "Izvēlies plānu, lai turpinātu.",
} satisfies OnboardingContent;
