import type { Locale } from "@/content";
const en = {
  title: "Team",
  intro: "Manage your team’s access to MemberFlow.",
  invite: "Invite team member",
  emptyTitle: "You’re working here on your own.",
  emptyText:
    "Invite colleagues to scan customers and perform the actions you allow.",
  member: "Team member",
  role: "Role",
  status: "Status",
  lastActive: "Last activity",
  never: "No activity yet",
  email: "Email",
  send: "Send invitation",
  sending: "Sending…",
  close: "Close",
  cancel: "Cancel",
  save: "Save changes",
  saving: "Saving…",
  edit: "Manage access",
  remove: "Remove from business",
  deactivate: "Deactivate access",
  activate: "Reactivate access",
  resend: "Resend invitation",
  revoke: "Revoke invitation",
  invited: "Invitation pending",
  invitationHeading: "Invitations",
  error: "We couldn’t update the team. Please try again.",
  loadError: "We couldn’t load the team.",
  retry: "Try again",
  saved: "Team updated.",
  previewSaved:
    "Preview updated. No invitation email was sent and no real access changed.",
  ownerProtected:
    "Ownership changes require a separate, backend-verified process.",
  confirmRemove: "Remove this team member?",
  confirmDeactivate: "Deactivate this team member’s access?",
  confirmRevoke: "Revoke this invitation?",
  confirm: "Confirm",
  joined: "Joined",
  you: "You",
  details: "Member details",
  noEmail: "Email not provided",
  active: "Active",
  inactive: "Inactive",
  pending: "Invitation pending",
  accepted: "Accepted",
  expired: "Expired",
  revoked: "Revoked",
};
export type TeamContent = { [K in keyof typeof en]: string };
const ru: TeamContent = {
  title: "Команда",
  intro: "Управляйте доступом сотрудников к MemberFlow.",
  invite: "Пригласить сотрудника",
  emptyTitle: "Вы пока работаете здесь один.",
  emptyText:
    "Пригласите сотрудников, чтобы они могли сканировать клиентов и выполнять разрешённые действия.",
  member: "Сотрудник",
  role: "Роль",
  status: "Статус",
  lastActive: "Последняя активность",
  never: "Активности пока нет",
  email: "Email",
  send: "Отправить приглашение",
  sending: "Отправляем…",
  close: "Закрыть",
  cancel: "Отмена",
  save: "Сохранить изменения",
  saving: "Сохраняем…",
  edit: "Управлять доступом",
  remove: "Удалить из бизнеса",
  deactivate: "Деактивировать доступ",
  activate: "Восстановить доступ",
  resend: "Повторить приглашение",
  revoke: "Отозвать приглашение",
  invited: "Ожидает приглашения",
  invitationHeading: "Приглашения",
  error: "Не удалось обновить команду. Попробуйте ещё раз.",
  loadError: "Не удалось загрузить команду.",
  retry: "Повторить",
  saved: "Команда обновлена.",
  previewSaved:
    "Превью обновлено. Письмо не отправлено, реальный доступ не изменён.",
  ownerProtected:
    "Изменение владельца требует отдельной процедуры с проверкой backend.",
  confirmRemove: "Удалить сотрудника из бизнеса?",
  confirmDeactivate: "Деактивировать доступ сотрудника?",
  confirmRevoke: "Отозвать приглашение?",
  confirm: "Подтвердить",
  joined: "Присоединился",
  you: "Вы",
  details: "Данные сотрудника",
  noEmail: "Email не указан",
  active: "Активен",
  inactive: "Неактивен",
  pending: "Ожидает приглашения",
  accepted: "Принято",
  expired: "Истекло",
  revoked: "Отозвано",
};
const lv: TeamContent = {
  title: "Komanda",
  intro: "Pārvaldiet darbinieku piekļuvi MemberFlow.",
  invite: "Uzaicināt darbinieku",
  emptyTitle: "Pagaidām šeit strādājat viens.",
  emptyText: "Uzaiciniet kolēģus skenēt klientus un veikt atļautās darbības.",
  member: "Darbinieks",
  role: "Loma",
  status: "Statuss",
  lastActive: "Pēdējā aktivitāte",
  never: "Vēl nav aktivitātes",
  email: "E-pasts",
  send: "Nosūtīt uzaicinājumu",
  sending: "Nosūta…",
  close: "Aizvērt",
  cancel: "Atcelt",
  save: "Saglabāt izmaiņas",
  saving: "Saglabā…",
  edit: "Pārvaldīt piekļuvi",
  remove: "Noņemt no uzņēmuma",
  deactivate: "Deaktivizēt piekļuvi",
  activate: "Atjaunot piekļuvi",
  resend: "Atkārtot uzaicinājumu",
  revoke: "Atsaukt uzaicinājumu",
  invited: "Gaida uzaicinājumu",
  invitationHeading: "Uzaicinājumi",
  error: "Neizdevās atjaunināt komandu. Mēģiniet vēlreiz.",
  loadError: "Neizdevās ielādēt komandu.",
  retry: "Mēģināt vēlreiz",
  saved: "Komanda atjaunināta.",
  previewSaved:
    "Priekšskatījums atjaunināts. E-pasts nav nosūtīts, faktiskā piekļuve nav mainīta.",
  ownerProtected:
    "Īpašnieka maiņai nepieciešama atsevišķa serverī pārbaudīta procedūra.",
  confirmRemove: "Noņemt šo darbinieku no uzņēmuma?",
  confirmDeactivate: "Deaktivizēt darbinieka piekļuvi?",
  confirmRevoke: "Atsaukt šo uzaicinājumu?",
  confirm: "Apstiprināt",
  joined: "Pievienojās",
  you: "Jūs",
  details: "Darbinieka dati",
  noEmail: "E-pasts nav norādīts",
  active: "Aktīvs",
  inactive: "Neaktīvs",
  pending: "Gaida uzaicinājumu",
  accepted: "Pieņemts",
  expired: "Beidzies",
  revoked: "Atsaukts",
};
export const teamContent: Record<Locale, TeamContent> = { en, lv, ru };
